{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "eventbus",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "fs5a3wgzhbh7vhn6vsygcvuxea"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "eventbus-0.1.jar",
          "url": "eventbus-0.1.jar",
          "size": 1539,
          "sha512": "5558add6333d746261a3b0284990bc49f706557dd127c3b2e2d8673a9d4dc33e0b2be937557de685c57801e290d76b11ee702e7c8653657540ac7abcfe452dd8",
          "sha256": "282241eaa5e15a4afa37590ef7dca0ce3c871d811264b75d8f21e04164f36837",
          "sha1": "feadb23a9d9187b13b0fef8c2c6113938f5c7dd6",
          "md5": "bc867a560933c2e63fe8ef96d601ee81"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "eventbus",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.spigotmc",
          "module": "spigot-api",
          "version": {
            "requires": "1.16.5-R0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "eventbus-0.1.jar",
          "url": "eventbus-0.1.jar",
          "size": 1539,
          "sha512": "5558add6333d746261a3b0284990bc49f706557dd127c3b2e2d8673a9d4dc33e0b2be937557de685c57801e290d76b11ee702e7c8653657540ac7abcfe452dd8",
          "sha256": "282241eaa5e15a4afa37590ef7dca0ce3c871d811264b75d8f21e04164f36837",
          "sha1": "feadb23a9d9187b13b0fef8c2c6113938f5c7dd6",
          "md5": "bc867a560933c2e63fe8ef96d601ee81"
        }
      ]
    }
  ]
}
