{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc.fancymodloader",
    "module": "loader",
    "version": "4.0.40",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "net.neoforged",
          "module": "mergetool",
          "version": {
            "requires": "2.0.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "mergetool",
              "type": "jar",
              "extension": "jar",
              "classifier": "api"
            }
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.22.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.8.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "cpw.mods",
          "module": "modlauncher",
          "version": {
            "requires": "11.0.3"
          }
        },
        {
          "group": "net.neoforged",
          "module": "coremods",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "com.mojang",
          "module": "logging",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "net.neoforged",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.neoforged",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.neoforged",
          "module": "bus",
          "version": {
            "requires": "8.0.5"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.mohistmc.fancymodloader",
          "module": "junit-fml",
          "version": {
            "requires": "4.0.40"
          }
        }
      ],
      "files": [
        {
          "name": "loader-4.0.40.jar",
          "url": "loader-4.0.40.jar",
          "size": 507897,
          "sha512": "cfbfbcb5963ff88c2328a49fe40708537d4aa32cf8657fa6508834ad5197f96c5492b9306497bd3c615f1844053019a7d65c81d5a9df78e08207fb70eb2a3cd6",
          "sha256": "f6e78475e570e05ae34c30a4a78d4945824699caa692e94341127816461ba72a",
          "sha1": "7e9d5433eaef340c5108cab7f58581cf89840ea3",
          "md5": "28f7dec9dd523a97fd7465af6630e2c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.neoforged",
          "module": "JarJarFileSystems",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "cpw.mods",
          "module": "securejarhandler",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "net.neoforged",
          "module": "accesstransformers",
          "version": {
            "requires": "10.0.1"
          }
        },
        {
          "group": "net.neoforged.accesstransformers",
          "module": "at-modlauncher",
          "version": {
            "requires": "10.0.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "modlauncher"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "sponge-mixin",
          "version": {
            "requires": "0.14.0+mixin.0.8.6"
          }
        },
        {
          "group": "net.minecrell",
          "module": "terminalconsoleappender",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.22.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "net.neoforged",
          "module": "mergetool",
          "version": {
            "requires": "2.0.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "mergetool",
              "type": "jar",
              "extension": "jar",
              "classifier": "api"
            }
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.22.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.8.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "cpw.mods",
          "module": "modlauncher",
          "version": {
            "requires": "11.0.3"
          }
        },
        {
          "group": "net.neoforged",
          "module": "coremods",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "com.mojang",
          "module": "logging",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "net.neoforged",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.neoforged",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.neoforged",
          "module": "bus",
          "version": {
            "requires": "8.0.5"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.mohistmc.fancymodloader",
          "module": "junit-fml",
          "version": {
            "requires": "4.0.40"
          }
        }
      ],
      "files": [
        {
          "name": "loader-4.0.40.jar",
          "url": "loader-4.0.40.jar",
          "size": 507897,
          "sha512": "cfbfbcb5963ff88c2328a49fe40708537d4aa32cf8657fa6508834ad5197f96c5492b9306497bd3c615f1844053019a7d65c81d5a9df78e08207fb70eb2a3cd6",
          "sha256": "f6e78475e570e05ae34c30a4a78d4945824699caa692e94341127816461ba72a",
          "sha1": "7e9d5433eaef340c5108cab7f58581cf89840ea3",
          "md5": "28f7dec9dd523a97fd7465af6630e2c9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "loader-4.0.40-sources.jar",
          "url": "loader-4.0.40-sources.jar",
          "size": 278193,
          "sha512": "2ad330e9e559898a47144f35e2f8522eba9682feb64adf1c7d296c2298e1419014326a09a52a126a7289807e0cffac6553d915077f8845d2a025918193c8c687",
          "sha256": "2f6d1dbd5a932e45765dabec4d4aacdaa4f0741948e26ecb9314d69c8435bf83",
          "sha1": "55950cc294c9fbb18e3381fc329c6eb489333824",
          "md5": "07daa5012acb2aeb42fa3ba2fcfe0996"
        }
      ]
    }
  ]
}
