{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc.miraimbot",
    "module": "annotations",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "c6nslpohu5ahhdacmlhzqr6h3a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20-RC"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-0.4.2.jar",
          "url": "annotations-0.4.2.jar",
          "size": 5108,
          "sha512": "b096d769fd4470575f478a10865da9cb232e1102725c971deb643b2b99abe0dbd4fcc2099e1dc1969e696bf700dca851617e6541b1733e04b70047a59481b01a",
          "sha256": "0d2e5db7aa064a86c20d003c3cb413db734fab9b6ef779c733c1149ddec5e785",
          "sha1": "9eed62f750c639bec26969b67bffe9abea18f380",
          "md5": "a8d97579d038c7bffbfa42047a45f6d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20-RC"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-0.4.2.jar",
          "url": "annotations-0.4.2.jar",
          "size": 5108,
          "sha512": "b096d769fd4470575f478a10865da9cb232e1102725c971deb643b2b99abe0dbd4fcc2099e1dc1969e696bf700dca851617e6541b1733e04b70047a59481b01a",
          "sha256": "0d2e5db7aa064a86c20d003c3cb413db734fab9b6ef779c733c1149ddec5e785",
          "sha1": "9eed62f750c639bec26969b67bffe9abea18f380",
          "md5": "a8d97579d038c7bffbfa42047a45f6d7"
        }
      ]
    }
  ]
}
