{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "youerdev",
    "version": "1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "youerdev-1.21.1.jar",
          "url": "youerdev-1.21.1.jar",
          "size": 103075074,
          "sha512": "b6cf9bd587cdf756c93812cb28e6ae655fc7b36cfd8d481f0b245c04137193fc9892d9e521e73d000826f28adcdab3d1e33834e6d255ee69c927c22fe9e657de",
          "sha256": "c569263eff7ad5f1cb22f52e4609070b241ba3d261683394af44aebfbc757514",
          "sha1": "e0c6ccfddd2c289142a7eee5f033568244d7f651",
          "md5": "c85302307809b1ae051947b5cb929ab4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "youerdev-1.21.1.jar",
          "url": "youerdev-1.21.1.jar",
          "size": 103075074,
          "sha512": "b6cf9bd587cdf756c93812cb28e6ae655fc7b36cfd8d481f0b245c04137193fc9892d9e521e73d000826f28adcdab3d1e33834e6d255ee69c927c22fe9e657de",
          "sha256": "c569263eff7ad5f1cb22f52e4609070b241ba3d261683394af44aebfbc757514",
          "sha1": "e0c6ccfddd2c289142a7eee5f033568244d7f651",
          "md5": "c85302307809b1ae051947b5cb929ab4"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "youerdev-1.21.1.jar",
          "url": "youerdev-1.21.1.jar",
          "size": 103075074,
          "sha512": "b6cf9bd587cdf756c93812cb28e6ae655fc7b36cfd8d481f0b245c04137193fc9892d9e521e73d000826f28adcdab3d1e33834e6d255ee69c927c22fe9e657de",
          "sha256": "c569263eff7ad5f1cb22f52e4609070b241ba3d261683394af44aebfbc757514",
          "sha1": "e0c6ccfddd2c289142a7eee5f033568244d7f651",
          "md5": "c85302307809b1ae051947b5cb929ab4"
        }
      ]
    }
  ]
}
