{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "youerdev",
    "version": "1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "youerdev-1.21.1.jar",
          "url": "youerdev-1.21.1.jar",
          "size": 101362941,
          "sha512": "759aa648d384d5407c3c07db4bb4c34d253d5f8b611c90cdc20078a928f50d1ce6026cbcabafa8ff2b9960cc52831998e19b97fda3eaeded77d34fbcc894df01",
          "sha256": "10efc71eb56cb9e9eb5eac1ab687db4a47043af276e4b2f13300906a74550cea",
          "sha1": "0caaa7c70e4e78425a2b342cadc4913b524acca7",
          "md5": "13fbf22067f4ac2e46662a986a03612d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "youerdev-1.21.1.jar",
          "url": "youerdev-1.21.1.jar",
          "size": 101362941,
          "sha512": "759aa648d384d5407c3c07db4bb4c34d253d5f8b611c90cdc20078a928f50d1ce6026cbcabafa8ff2b9960cc52831998e19b97fda3eaeded77d34fbcc894df01",
          "sha256": "10efc71eb56cb9e9eb5eac1ab687db4a47043af276e4b2f13300906a74550cea",
          "sha1": "0caaa7c70e4e78425a2b342cadc4913b524acca7",
          "md5": "13fbf22067f4ac2e46662a986a03612d"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "youerdev-1.21.1.jar",
          "url": "youerdev-1.21.1.jar",
          "size": 101362941,
          "sha512": "759aa648d384d5407c3c07db4bb4c34d253d5f8b611c90cdc20078a928f50d1ce6026cbcabafa8ff2b9960cc52831998e19b97fda3eaeded77d34fbcc894df01",
          "sha256": "10efc71eb56cb9e9eb5eac1ab687db4a47043af276e4b2f13300906a74550cea",
          "sha1": "0caaa7c70e4e78425a2b342cadc4913b524acca7",
          "md5": "13fbf22067f4ac2e46662a986a03612d"
        }
      ]
    }
  ]
}
