{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc.yaml",
    "module": "yaml",
    "version": "0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "yaml-0.3.jar",
          "url": "yaml-0.3.jar",
          "size": 34550,
          "sha512": "fe65c120ca5ed94bd47033b37080731871750b5f512fbe7ffda882daa8f02adf99a85a80e4672bbd5f2cb21ae1591e17115028c812271824fbe681bf4bd06a9d",
          "sha256": "151345d73bd6a402108c9094c05979cb5a110211970c8a98591ca19035564f57",
          "sha1": "e4e45bab6f133f54ad640de0cd890c64fb7d2774",
          "md5": "a40aec7ef275c816d2355c2ce1faeb8d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.33"
          }
        }
      ],
      "files": [
        {
          "name": "yaml-0.3.jar",
          "url": "yaml-0.3.jar",
          "size": 34550,
          "sha512": "fe65c120ca5ed94bd47033b37080731871750b5f512fbe7ffda882daa8f02adf99a85a80e4672bbd5f2cb21ae1591e17115028c812271824fbe681bf4bd06a9d",
          "sha256": "151345d73bd6a402108c9094c05979cb5a110211970c8a98591ca19035564f57",
          "sha1": "e4e45bab6f133f54ad640de0cd890c64fb7d2774",
          "md5": "a40aec7ef275c816d2355c2ce1faeb8d"
        }
      ]
    }
  ]
}
