{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "artifactural",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "artifactural-1.0.jar",
          "url": "artifactural-1.0.jar",
          "size": 56745,
          "sha512": "9446e5290040f7c2acf003968adc7b36f01fd81cba5fab90a4e382fde413a02b7b5aeebde787d3b18eee7f3cce376dcd86953fad7100f73ccd8cf2660398eab9",
          "sha256": "66148fd2eaa13b6caf4e5533e8fe87cc769ba5ace469ac27ab61b48d8ae24462",
          "sha1": "544f49d9194a0445d66a726446cafaeec01e0479",
          "md5": "b14dfe34e7807334adc82de02a53308b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "unsafe",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "artifactural-1.0.jar",
          "url": "artifactural-1.0.jar",
          "size": 56745,
          "sha512": "9446e5290040f7c2acf003968adc7b36f01fd81cba5fab90a4e382fde413a02b7b5aeebde787d3b18eee7f3cce376dcd86953fad7100f73ccd8cf2660398eab9",
          "sha256": "66148fd2eaa13b6caf4e5533e8fe87cc769ba5ace469ac27ab61b48d8ae24462",
          "sha1": "544f49d9194a0445d66a726446cafaeec01e0479",
          "md5": "b14dfe34e7807334adc82de02a53308b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "artifactural-1.0-sources.jar",
          "url": "artifactural-1.0-sources.jar",
          "size": 33908,
          "sha512": "06392127a176825fa32e483653590b7be1ca02c2e5ce5f8bc179cd328ddf396fa8294d995eaea917ec0085b812dec78e055d8aad673e8f94fc43881c76048f60",
          "sha256": "164530a5c16474c5b4144aaaa92e97b61dbe57f24bb05a817964bc0fb5ee7fb2",
          "sha1": "a0fbaad475a87ae7fbde5d774dd47b3ef774f149",
          "md5": "358329ab1d8b773a47a3a897d13f71c1"
        }
      ]
    }
  ]
}
