{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "artifactural",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "artifactural-1.0.jar",
          "url": "artifactural-1.0.jar",
          "size": 56745,
          "sha512": "9cda94cb3e4998581bd9f8543ad174c92aafcf2bb19df2a2f5a81564eba757459f1fc5d1ef047068e4792f422efe516d91be69e00ac5eeec6c4aa8d99ffc6a80",
          "sha256": "289fc80f9c0f71c46602c39bd5a765793ee81d41f73d74c9532904294496d52b",
          "sha1": "3dacbd24e3d6559bd4a57642e826ab9fd573e468",
          "md5": "6a5fcd7fa9c2077806188f7dcc797a4e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "unsafe",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "artifactural-1.0.jar",
          "url": "artifactural-1.0.jar",
          "size": 56745,
          "sha512": "9cda94cb3e4998581bd9f8543ad174c92aafcf2bb19df2a2f5a81564eba757459f1fc5d1ef047068e4792f422efe516d91be69e00ac5eeec6c4aa8d99ffc6a80",
          "sha256": "289fc80f9c0f71c46602c39bd5a765793ee81d41f73d74c9532904294496d52b",
          "sha1": "3dacbd24e3d6559bd4a57642e826ab9fd573e468",
          "md5": "6a5fcd7fa9c2077806188f7dcc797a4e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "artifactural-1.0-sources.jar",
          "url": "artifactural-1.0-sources.jar",
          "size": 33908,
          "sha512": "06392127a176825fa32e483653590b7be1ca02c2e5ce5f8bc179cd328ddf396fa8294d995eaea917ec0085b812dec78e055d8aad673e8f94fc43881c76048f60",
          "sha256": "164530a5c16474c5b4144aaaa92e97b61dbe57f24bb05a817964bc0fb5ee7fb2",
          "sha1": "a0fbaad475a87ae7fbde5d774dd47b3ef774f149",
          "md5": "358329ab1d8b773a47a3a897d13f71c1"
        }
      ]
    }
  ]
}
