{
  "formatVersion": "1.1",
  "component": {
    "group": "cpw.mods",
    "module": "securejarhandler",
    "version": "mohist-2.1.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.5"
          }
        }
      ],
      "files": [
        {
          "name": "securejarhandler-mohist-2.1.12.jar",
          "url": "securejarhandler-mohist-2.1.12.jar",
          "size": 89109,
          "sha512": "b678b2cc27dc8935b2c47bf33e056f5a2d7c19bb0776cc98a2fd4556682bed718064707e1c66ae1ef93299f93d4e1d01a347c258fe933c03b2133cbc4e07d5a2",
          "sha256": "63fe277c578b779c8336b0bc52cf731b746d3ab32ec392f4ef6ad7211b002be6",
          "sha1": "21efaeb1e94b87bf7fbbf123a684491d0ee4683c",
          "md5": "01df862aaf83f857a356e7c165da3136"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "unsafe",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.5"
          }
        }
      ],
      "files": [
        {
          "name": "securejarhandler-mohist-2.1.12.jar",
          "url": "securejarhandler-mohist-2.1.12.jar",
          "size": 89109,
          "sha512": "b678b2cc27dc8935b2c47bf33e056f5a2d7c19bb0776cc98a2fd4556682bed718064707e1c66ae1ef93299f93d4e1d01a347c258fe933c03b2133cbc4e07d5a2",
          "sha256": "63fe277c578b779c8336b0bc52cf731b746d3ab32ec392f4ef6ad7211b002be6",
          "sha1": "21efaeb1e94b87bf7fbbf123a684491d0ee4683c",
          "md5": "01df862aaf83f857a356e7c165da3136"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "securejarhandler-mohist-2.1.12-sources.jar",
          "url": "securejarhandler-mohist-2.1.12-sources.jar",
          "size": 31245,
          "sha512": "1ef3fcf4721c74e6c98b1231b4d90bc6204f4dadfd6d601e0915df291d7e411671a1c1267f5bbe3bfbba7b3f81bc5717abd399edfc0aa74c530aeaa818f9cdb3",
          "sha256": "b369120e42e99e5091628864e5d46d24a45c121ec365bc5a40cff4b6e1276504",
          "sha1": "716941716b35386f91e118462ff23bd053fce299",
          "md5": "531e0217a11ecb48dcee326e1d5cac00"
        }
      ]
    }
  ]
}
