{
  "formatVersion": "1.1",
  "component": {
    "group": "net.minecraftforge",
    "module": "securejarhandler",
    "version": "mohist-2.1.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.5"
          }
        }
      ],
      "files": [
        {
          "name": "securejarhandler-mohist-2.1.12.jar",
          "url": "securejarhandler-mohist-2.1.12.jar",
          "size": 89109,
          "sha512": "143286d91c8341494df5078758ef6046cb23893de05ce7fc39295c9d979160daff9774b3ec129c5cfd578762aa73f9f8c4c66e292a4766198cf95b67f020c14c",
          "sha256": "02c983217b77c1b38d3dac4a95faf70da06609a222861b660b03358188f54e06",
          "sha1": "b21a750cb12add3ac3294bfa6fc2600ca194fc69",
          "md5": "a7e99a9937dcadb7f17e813b5f6cc68c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "unsafe",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.5"
          }
        }
      ],
      "files": [
        {
          "name": "securejarhandler-mohist-2.1.12.jar",
          "url": "securejarhandler-mohist-2.1.12.jar",
          "size": 89109,
          "sha512": "143286d91c8341494df5078758ef6046cb23893de05ce7fc39295c9d979160daff9774b3ec129c5cfd578762aa73f9f8c4c66e292a4766198cf95b67f020c14c",
          "sha256": "02c983217b77c1b38d3dac4a95faf70da06609a222861b660b03358188f54e06",
          "sha1": "b21a750cb12add3ac3294bfa6fc2600ca194fc69",
          "md5": "a7e99a9937dcadb7f17e813b5f6cc68c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "securejarhandler-mohist-2.1.12-sources.jar",
          "url": "securejarhandler-mohist-2.1.12-sources.jar",
          "size": 31245,
          "sha512": "17b8a34bc27802d36a9e7875d163152c08d29c230a14745ced843a2262997c1a9e081e594a9150d9be1f4a9e4237efcdf97e8b492bbbbf7d7cf1186e6d2d2d39",
          "sha256": "262ef676b60e2ef9a59a0b50944cee6664f880185eac921c889fa5824b170bf0",
          "sha1": "6bb3f9398f37dd76c0ebd0878985072a1024be16",
          "md5": "d788d9ab2e3b4178e449ecd616ad2f74"
        }
      ]
    }
  ]
}
