{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "SpecialSource",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "SpecialSource-1.0.jar",
          "url": "SpecialSource-1.0.jar",
          "size": 6517653,
          "sha512": "66a1a7acf162162929e87bcdccfd3422d139a2ed14395ad3e5e02c4694e05a65eef800d3ab4dc5996f1bb90527ecf8604b7c8a5c8f7287c6d74c9dd1c71b79b0",
          "sha256": "7b7e8455b8c609b4af73da320fe8fd5c0eeeab5e034384447ed8520b23239119",
          "sha1": "7b4a57e8b6e2fae5dcdf7c1765a780d3e0b1655f",
          "md5": "f66da69187be6fe317264eb283969a4f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.8.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "com.opencsv",
          "module": "opencsv",
          "version": {
            "requires": "5.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "SpecialSource-1.0.jar",
          "url": "SpecialSource-1.0.jar",
          "size": 6517653,
          "sha512": "66a1a7acf162162929e87bcdccfd3422d139a2ed14395ad3e5e02c4694e05a65eef800d3ab4dc5996f1bb90527ecf8604b7c8a5c8f7287c6d74c9dd1c71b79b0",
          "sha256": "7b7e8455b8c609b4af73da320fe8fd5c0eeeab5e034384447ed8520b23239119",
          "sha1": "7b4a57e8b6e2fae5dcdf7c1765a780d3e0b1655f",
          "md5": "f66da69187be6fe317264eb283969a4f"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "SpecialSource-1.0.jar",
          "url": "SpecialSource-1.0.jar",
          "size": 6517653,
          "sha512": "66a1a7acf162162929e87bcdccfd3422d139a2ed14395ad3e5e02c4694e05a65eef800d3ab4dc5996f1bb90527ecf8604b7c8a5c8f7287c6d74c9dd1c71b79b0",
          "sha256": "7b7e8455b8c609b4af73da320fe8fd5c0eeeab5e034384447ed8520b23239119",
          "sha1": "7b4a57e8b6e2fae5dcdf7c1765a780d3e0b1655f",
          "md5": "f66da69187be6fe317264eb283969a4f"
        }
      ]
    }
  ]
}
