{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc.gradle",
    "module": "MohistGradle",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "MohistGradle-1.0.jar",
          "url": "MohistGradle-1.0.jar",
          "size": 453693,
          "sha512": "5e7a811fa0aaca7b049f2ac2ad578033afb5489cbe5957a961f87b8ac893218c5d5a51c9b9da9371fd671a839d6315722e71e4999402ebc46ffda14054349e37",
          "sha256": "e036e7b4dae7d38dda976e54f2a6cdb5ed9b38e3a49e85e4990f8ed30a17a6e4",
          "sha1": "9708ddcd7954738fad34682024d2b7a0c8785e06",
          "md5": "b5432aaf65e70f1975e42be612b613e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "artifactural",
          "version": {
            "requires": "3.0.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "unsafe",
          "version": {
            "requires": "0.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.6.3"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.13"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.4.13"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "DiffPatch",
          "version": {
            "requires": "2.0.7"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "DiffPatch",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.3.17"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.3.17"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "MohistGradle-1.0.jar",
          "url": "MohistGradle-1.0.jar",
          "size": 453693,
          "sha512": "5e7a811fa0aaca7b049f2ac2ad578033afb5489cbe5957a961f87b8ac893218c5d5a51c9b9da9371fd671a839d6315722e71e4999402ebc46ffda14054349e37",
          "sha256": "e036e7b4dae7d38dda976e54f2a6cdb5ed9b38e3a49e85e4990f8ed30a17a6e4",
          "sha1": "9708ddcd7954738fad34682024d2b7a0c8785e06",
          "md5": "b5432aaf65e70f1975e42be612b613e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "MohistGradle-1.0-sources.jar",
          "url": "MohistGradle-1.0-sources.jar",
          "size": 241938,
          "sha512": "dde558dfd8e4b53031bc02d50e616cadddf0b5cbf5eaf38e4b6b6ca44b22b08142fe3116ab58b6a61691b84a6156443020b3f554ed305f3c898124995c093428",
          "sha256": "7bcb10e05ce4a0478e317d7602b85eccd901da7e1e63f99d92327a7869f1b2ea",
          "sha1": "724cffb5349740072c99ed1f5bb194b53f70957a",
          "md5": "80603798f168f70e6b495818d61486a2"
        }
      ]
    }
  ]
}
