{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc.gradle",
    "module": "MohistGradle",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "MohistGradle-1.0.jar",
          "url": "MohistGradle-1.0.jar",
          "size": 453692,
          "sha512": "0eead407a9f2a7bf3ff42263d61a296dc09ef1a3aa8dc71569f5b7bef879c0cf556d3688ca80d6626624e2514261a72db6ce0b96d86d77390f35d3a4842e7e08",
          "sha256": "ffc3ed604ef9395df579a537afbede8b9c2ec041169f935180536a15cdb0a65c",
          "sha1": "225e86c6ae6ec1e0d0224c1f53d78bacd127abda",
          "md5": "c47aa6011edcd3062c9020c83d88ee59"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "artifactural",
          "version": {
            "requires": "3.0.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "unsafe",
          "version": {
            "requires": "0.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.6.3"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.13"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.4.13"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "DiffPatch",
          "version": {
            "requires": "2.0.7"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "DiffPatch",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.3.17"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.3.17"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "MohistGradle-1.0.jar",
          "url": "MohistGradle-1.0.jar",
          "size": 453692,
          "sha512": "0eead407a9f2a7bf3ff42263d61a296dc09ef1a3aa8dc71569f5b7bef879c0cf556d3688ca80d6626624e2514261a72db6ce0b96d86d77390f35d3a4842e7e08",
          "sha256": "ffc3ed604ef9395df579a537afbede8b9c2ec041169f935180536a15cdb0a65c",
          "sha1": "225e86c6ae6ec1e0d0224c1f53d78bacd127abda",
          "md5": "c47aa6011edcd3062c9020c83d88ee59"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "MohistGradle-1.0-sources.jar",
          "url": "MohistGradle-1.0-sources.jar",
          "size": 241935,
          "sha512": "f27e22d34a08cc76a6b68c5798c9d2182fa1d824fe2c4c7a1d97546f46942abec7d6dac9cafba7f435f4c21ef4bdb53182890fd02a69f4c6989647ccc1ae4b53",
          "sha256": "bb0fb7b0f9119f81d3ecdef60cff78d8cd813ff2706388f96609347f8fc978b0",
          "sha1": "a2d2bad2eb770e67e339527f3f37835d22bb4806",
          "md5": "128b67c6adf72d74d1ec97880889e38f"
        }
      ]
    }
  ]
}
