{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc.enumhelper",
    "module": "enumhelper",
    "version": "1.16.5-0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "enumhelper-1.16.5-0.1.jar",
          "url": "enumhelper-1.16.5-0.1.jar",
          "size": 6780,
          "sha512": "327d09f9e700d4f2108f78b1321355cc89dbd08640d719ef81753a77bba62e76ede1cbbd25508ab8cff41f9c9453647a4672f9c1136ca1b2c2574511723c3916",
          "sha256": "fb141c998116bb43477ced7a88baadbd1820ee0707aaf5347c9434532186f7b7",
          "sha1": "64a7fcf243b9892993b889bef058b5d8e185d5e0",
          "md5": "3bd4da8e1f569ee2921572e080f6ec41"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "enumhelper-1.16.5-0.1.jar",
          "url": "enumhelper-1.16.5-0.1.jar",
          "size": 6780,
          "sha512": "327d09f9e700d4f2108f78b1321355cc89dbd08640d719ef81753a77bba62e76ede1cbbd25508ab8cff41f9c9453647a4672f9c1136ca1b2c2574511723c3916",
          "sha256": "fb141c998116bb43477ced7a88baadbd1820ee0707aaf5347c9434532186f7b7",
          "sha1": "64a7fcf243b9892993b889bef058b5d8e185d5e0",
          "md5": "3bd4da8e1f569ee2921572e080f6ec41"
        }
      ]
    }
  ]
}
