{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "dynamicenum",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dynamicenum-0.3.1.jar",
          "url": "dynamicenum-0.3.1.jar",
          "size": 3955,
          "sha512": "8aae5dd6072e806b754c31b95f0f3892721d357c603ff66089936d759f8598ab0c3b15a8570e2112ecfc23cc67f9b64a1a0463a2984b9e4a45df54cfba29a866",
          "sha256": "94342d0a27e2c2bc9ef057cdf0aecda2e5562cfb71f94bc18b4c466bda6dc976",
          "sha1": "e94c6bd4f48ecc6d9bef92344dcd06fd6e28cbb8",
          "md5": "c6cab26e82cc2440ab518907006acf23"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dynamicenum-0.3.1.jar",
          "url": "dynamicenum-0.3.1.jar",
          "size": 3955,
          "sha512": "8aae5dd6072e806b754c31b95f0f3892721d357c603ff66089936d759f8598ab0c3b15a8570e2112ecfc23cc67f9b64a1a0463a2984b9e4a45df54cfba29a866",
          "sha256": "94342d0a27e2c2bc9ef057cdf0aecda2e5562cfb71f94bc18b4c466bda6dc976",
          "sha1": "e94c6bd4f48ecc6d9bef92344dcd06fd6e28cbb8",
          "md5": "c6cab26e82cc2440ab518907006acf23"
        }
      ]
    }
  ]
}
