{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "tools",
    "version": "0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tools-0.2.jar",
          "url": "tools-0.2.jar",
          "size": 1980034,
          "sha512": "ebeddff5a00ebab1c4e863f468f9139d3a2b9a9d5a729c67a6978c73fa6266bd7aa1d1352880f1b7ca722ead96016f4675d54b62cf32f8a8aa0354681d513e9c",
          "sha256": "51868d4f99c57e124eef96621980d04f6774d11bf9404e29c62c0dcaa770eb9b",
          "sha1": "1991f118d05b5db09c72118814d47814db3b54aa",
          "md5": "c71f62e94bff725a43aa0549ed9ab121"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tools-0.2.jar",
          "url": "tools-0.2.jar",
          "size": 1980034,
          "sha512": "ebeddff5a00ebab1c4e863f468f9139d3a2b9a9d5a729c67a6978c73fa6266bd7aa1d1352880f1b7ca722ead96016f4675d54b62cf32f8a8aa0354681d513e9c",
          "sha256": "51868d4f99c57e124eef96621980d04f6774d11bf9404e29c62c0dcaa770eb9b",
          "sha1": "1991f118d05b5db09c72118814d47814db3b54aa",
          "md5": "c71f62e94bff725a43aa0549ed9ab121"
        }
      ]
    }
  ]
}
