{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "dynamicenum",
    "version": "0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dynamicenum-0.2.jar",
          "url": "dynamicenum-0.2.jar",
          "size": 3862,
          "sha512": "2d14fa658292c1fd70d221a43562c6c98823c67f5c6686ebab460ff32be3f2e2b1e1bb71bf573ac9478e34a9b24382952e80be3c334165cf17f51ee629cc1f62",
          "sha256": "4f264d7c8fcea952cfee317a79c4a978859bc2089aeb3c18d039da3b0f1f572a",
          "sha1": "91b218bd6578eec0c50a47db18df5009d64a3cf2",
          "md5": "4645b00a2582ef68cf40c900ff4f7d68"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dynamicenum-0.2.jar",
          "url": "dynamicenum-0.2.jar",
          "size": 3862,
          "sha512": "2d14fa658292c1fd70d221a43562c6c98823c67f5c6686ebab460ff32be3f2e2b1e1bb71bf573ac9478e34a9b24382952e80be3c334165cf17f51ee629cc1f62",
          "sha256": "4f264d7c8fcea952cfee317a79c4a978859bc2089aeb3c18d039da3b0f1f572a",
          "sha1": "91b218bd6578eec0c50a47db18df5009d64a3cf2",
          "md5": "4645b00a2582ef68cf40c900ff4f7d68"
        }
      ]
    }
  ]
}
