{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "miraimbot",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "a7jnudnibbcfnevp7f7k3alf3a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.mamoe",
          "module": "mirai-core",
          "version": {
            "requires": "2.7-M1"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.75"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "net.minecrell",
          "module": "terminalconsoleappender",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-terminal-jansi",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-terminal-jna",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-reader",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.20"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "21.0"
          }
        },
        {
          "group": "com.mohistmc.yaml",
          "module": "Yaml",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20-RC"
          }
        }
      ],
      "files": [
        {
          "name": "miraimbot-0.4.1.jar",
          "url": "miraimbot-0.4.1.jar",
          "size": 1371465,
          "sha512": "4f0cecde340424bce1d8d236df63d94dff1b9aa532237f01590667dbcaeb2fec4b085e69c19dcb1d6ab280b8d7c5acddc5746bf115f7dd14495c9de0fd6ad9af",
          "sha256": "388a2897d37ef2a89bb3536ebd80bcd06e43bbc00fde0273486eaa2288175e11",
          "sha1": "548d6a7586dc9a5b959ec41ede8216c509f712ae",
          "md5": "049a51421a0c2cccfb65e5a506ab6e8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.mamoe",
          "module": "mirai-core",
          "version": {
            "requires": "2.7-M1"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.75"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "net.minecrell",
          "module": "terminalconsoleappender",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-terminal-jansi",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-terminal-jna",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-reader",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.20"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "21.0"
          }
        },
        {
          "group": "com.mohistmc.yaml",
          "module": "Yaml",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20-RC"
          }
        }
      ],
      "files": [
        {
          "name": "miraimbot-0.4.1.jar",
          "url": "miraimbot-0.4.1.jar",
          "size": 1371465,
          "sha512": "4f0cecde340424bce1d8d236df63d94dff1b9aa532237f01590667dbcaeb2fec4b085e69c19dcb1d6ab280b8d7c5acddc5746bf115f7dd14495c9de0fd6ad9af",
          "sha256": "388a2897d37ef2a89bb3536ebd80bcd06e43bbc00fde0273486eaa2288175e11",
          "sha1": "548d6a7586dc9a5b959ec41ede8216c509f712ae",
          "md5": "049a51421a0c2cccfb65e5a506ab6e8b"
        }
      ]
    }
  ]
}
