{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "librariesvault",
    "version": "1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "librariesvault-1.20.1.jar",
          "url": "librariesvault-1.20.1.jar",
          "size": 344470,
          "sha512": "eff5345fbf2fc1c4be69d59c98f886a49f4a5c6b3e1f4852397a415797c3ddd351a0115abbaf19467f8c4abb249898bfbeca486134294563bfc4826419d1c348",
          "sha256": "2f5be204480661277db4a75b248becdc341747b5044d0bb7cb59573f2cccbbcf",
          "sha1": "9366dfc59d15616e5dadcb3ad4e0cf1a4a6e418b",
          "md5": "3e21619cc3900fcf1534eee834b5cd26"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        }
      ],
      "files": [
        {
          "name": "librariesvault-1.20.1.jar",
          "url": "librariesvault-1.20.1.jar",
          "size": 344470,
          "sha512": "eff5345fbf2fc1c4be69d59c98f886a49f4a5c6b3e1f4852397a415797c3ddd351a0115abbaf19467f8c4abb249898bfbeca486134294563bfc4826419d1c348",
          "sha256": "2f5be204480661277db4a75b248becdc341747b5044d0bb7cb59573f2cccbbcf",
          "sha1": "9366dfc59d15616e5dadcb3ad4e0cf1a4a6e418b",
          "md5": "3e21619cc3900fcf1534eee834b5cd26"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "librariesvault-1.20.1.jar",
          "url": "librariesvault-1.20.1.jar",
          "size": 344470,
          "sha512": "eff5345fbf2fc1c4be69d59c98f886a49f4a5c6b3e1f4852397a415797c3ddd351a0115abbaf19467f8c4abb249898bfbeca486134294563bfc4826419d1c348",
          "sha256": "2f5be204480661277db4a75b248becdc341747b5044d0bb7cb59573f2cccbbcf",
          "sha1": "9366dfc59d15616e5dadcb3ad4e0cf1a4a6e418b",
          "md5": "3e21619cc3900fcf1534eee834b5cd26"
        }
      ]
    }
  ]
}
