{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "libraries",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libraries-0.2.1.jar",
          "url": "libraries-0.2.1.jar",
          "size": 7323,
          "sha512": "0f9ce2ebc1b2b379dce09f7ae22fd91452ad00389bd9b7281b984634eb418c73f2548897bf2a513f5863ede6e53c75a7f47899aac3e335935982d8c1eaa3ae4d",
          "sha256": "0f327d460e7c7c194fe7e115a0c6cbdc9e369c5bf54f95596629f62e535a55f9",
          "sha1": "ba7d791b3fc6512efb82e10e4f708808bca172aa",
          "md5": "a73f1047225ccc8d1468abe14be8d41c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mohistmc",
          "module": "tools",
          "version": {
            "requires": "0.4"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "libraries-0.2.1.jar",
          "url": "libraries-0.2.1.jar",
          "size": 7323,
          "sha512": "0f9ce2ebc1b2b379dce09f7ae22fd91452ad00389bd9b7281b984634eb418c73f2548897bf2a513f5863ede6e53c75a7f47899aac3e335935982d8c1eaa3ae4d",
          "sha256": "0f327d460e7c7c194fe7e115a0c6cbdc9e369c5bf54f95596629f62e535a55f9",
          "sha1": "ba7d791b3fc6512efb82e10e4f708808bca172aa",
          "md5": "a73f1047225ccc8d1468abe14be8d41c"
        }
      ]
    }
  ]
}
