{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "libraries",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libraries-0.2.1.jar",
          "url": "libraries-0.2.1.jar",
          "size": 7330,
          "sha512": "711406b0d0b6b9cc51e3e2734d89358bbd623834a1bc616ca6c47a95a95bd888fa9c3cab8b8e5eb1d8d831ee9b5c77d1ee9f8e75458ba6a300cd89987af61c31",
          "sha256": "2572550d9e6181b8f524abcbac334fa521e1a02f0eb89a743ec4c166db78558c",
          "sha1": "518c7a1abc5b46f1eb93021d478ad8afadb2d3e3",
          "md5": "ec133c3d41c5cbdb65901d7890eb24f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mohistmc",
          "module": "tools",
          "version": {
            "requires": "0.4"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "libraries-0.2.1.jar",
          "url": "libraries-0.2.1.jar",
          "size": 7330,
          "sha512": "711406b0d0b6b9cc51e3e2734d89358bbd623834a1bc616ca6c47a95a95bd888fa9c3cab8b8e5eb1d8d831ee9b5c77d1ee9f8e75458ba6a300cd89987af61c31",
          "sha256": "2572550d9e6181b8f524abcbac334fa521e1a02f0eb89a743ec4c166db78558c",
          "sha1": "518c7a1abc5b46f1eb93021d478ad8afadb2d3e3",
          "md5": "ec133c3d41c5cbdb65901d7890eb24f1"
        }
      ]
    }
  ]
}
