{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "librariesvault",
    "version": "1.20.1-0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "librariesvault-1.20.1-0.1.jar",
          "url": "librariesvault-1.20.1-0.1.jar",
          "size": 13378217,
          "sha512": "ab26213fa3ab44b511c2aa8c9b529b80843946af0466230554956368c6c021de43d66b110e4d590106bad27c20a47332885520f825d336cc222f9b4bde4ed208",
          "sha256": "d7560f96e302e2841501f4a56e0d7e18d45684171f408af8d6521ed92df18e82",
          "sha1": "aebcac32b1375a53bbe6212fa383ffe5c6ae56d1",
          "md5": "6cfb75fef68ba7fa6e845abbba99c3e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "org.xerial",
          "module": "sqlite-jdbc",
          "version": {
            "requires": "3.42.0.0"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        }
      ],
      "files": [
        {
          "name": "librariesvault-1.20.1-0.1.jar",
          "url": "librariesvault-1.20.1-0.1.jar",
          "size": 13378217,
          "sha512": "ab26213fa3ab44b511c2aa8c9b529b80843946af0466230554956368c6c021de43d66b110e4d590106bad27c20a47332885520f825d336cc222f9b4bde4ed208",
          "sha256": "d7560f96e302e2841501f4a56e0d7e18d45684171f408af8d6521ed92df18e82",
          "sha1": "aebcac32b1375a53bbe6212fa383ffe5c6ae56d1",
          "md5": "6cfb75fef68ba7fa6e845abbba99c3e0"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "librariesvault-1.20.1-0.1.jar",
          "url": "librariesvault-1.20.1-0.1.jar",
          "size": 13378217,
          "sha512": "ab26213fa3ab44b511c2aa8c9b529b80843946af0466230554956368c6c021de43d66b110e4d590106bad27c20a47332885520f825d336cc222f9b4bde4ed208",
          "sha256": "d7560f96e302e2841501f4a56e0d7e18d45684171f408af8d6521ed92df18e82",
          "sha1": "aebcac32b1375a53bbe6212fa383ffe5c6ae56d1",
          "md5": "6cfb75fef68ba7fa6e845abbba99c3e0"
        }
      ]
    }
  ]
}
