{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "MiraiMBot",
    "version": "0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "q5na4h4qmrbixkxtpr63b27zbq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.mamoe",
          "module": "mirai-core",
          "version": {
            "requires": "2.7-M1"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.75"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "net.minecrell",
          "module": "terminalconsoleappender",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-terminal-jansi",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-terminal-jna",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-reader",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.8"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "21.0"
          }
        },
        {
          "group": "com.mohistmc.yaml",
          "module": "Yaml",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "net.md-5",
          "module": "bungeecord-chat",
          "version": {
            "requires": "1.12-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20-RC"
          }
        }
      ],
      "files": [
        {
          "name": "MiraiMBot-0.4-SNAPSHOT.jar",
          "url": "MiraiMBot-0.4-SNAPSHOT.jar",
          "size": 1371495,
          "sha512": "77daefb2ea85e8948fe983ad49223092428c65e302d39cdff6403ec9b9828da502aea8a2e2fa7c03649381864c8b2b9882f4cdfc9bb7cf8f16a96f7bf02e80eb",
          "sha256": "bd7feae47ed9d39a98160f046636e5411dd7f1f84bad0540df38e1484cc7cc71",
          "sha1": "12322157cace9caa70b6fbd81b99b0a4b73f8b2b",
          "md5": "f899c1bf5b7040f8b9b6f199da536ffd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.mamoe",
          "module": "mirai-core",
          "version": {
            "requires": "2.7-M1"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.75"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "net.minecrell",
          "module": "terminalconsoleappender",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-terminal-jansi",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-terminal-jna",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-reader",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.8"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "21.0"
          }
        },
        {
          "group": "com.mohistmc.yaml",
          "module": "Yaml",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "net.md-5",
          "module": "bungeecord-chat",
          "version": {
            "requires": "1.12-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20-RC"
          }
        }
      ],
      "files": [
        {
          "name": "MiraiMBot-0.4-SNAPSHOT.jar",
          "url": "MiraiMBot-0.4-SNAPSHOT.jar",
          "size": 1371495,
          "sha512": "77daefb2ea85e8948fe983ad49223092428c65e302d39cdff6403ec9b9828da502aea8a2e2fa7c03649381864c8b2b9882f4cdfc9bb7cf8f16a96f7bf02e80eb",
          "sha256": "bd7feae47ed9d39a98160f046636e5411dd7f1f84bad0540df38e1484cc7cc71",
          "sha1": "12322157cace9caa70b6fbd81b99b0a4b73f8b2b",
          "md5": "f899c1bf5b7040f8b9b6f199da536ffd"
        }
      ]
    }
  ]
}
