{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc.yaml",
    "module": "Yaml",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "njb42xcojvgvjfnq45tussbyya"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.26"
          }
        }
      ],
      "files": [
        {
          "name": "Yaml-0.1.jar",
          "url": "Yaml-0.1.jar",
          "size": 338558,
          "sha512": "d3455d4ca7086aa06464fac1b8a64a8fdace507029e53ff66c1314aa31f0daaa3a15cc55ca27ffa8048a885e6f471e2a1a13df1482237e7c65b4432c11f65d2e",
          "sha256": "fc2babf511975ddda7f263986a2702c2fb7e4a4836e03167ea9e0c6d91e51cf3",
          "sha1": "e4658e312b037acd035f5ff9fcb6294e0c7a75a1",
          "md5": "9f3e1e6365ba8d3b66b1cd6f95db5664"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.26"
          }
        }
      ],
      "files": [
        {
          "name": "Yaml-0.1.jar",
          "url": "Yaml-0.1.jar",
          "size": 338558,
          "sha512": "d3455d4ca7086aa06464fac1b8a64a8fdace507029e53ff66c1314aa31f0daaa3a15cc55ca27ffa8048a885e6f471e2a1a13df1482237e7c65b4432c11f65d2e",
          "sha256": "fc2babf511975ddda7f263986a2702c2fb7e4a4836e03167ea9e0c6d91e51cf3",
          "sha1": "e4658e312b037acd035f5ff9fcb6294e0c7a75a1",
          "md5": "9f3e1e6365ba8d3b66b1cd6f95db5664"
        }
      ]
    }
  ]
}
