{
  "formatVersion": "1.1",
  "component": {
    "group": "net.minecraftforge",
    "module": "securejarhandler",
    "version": "mohist-2.1.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.3"
          }
        }
      ],
      "files": [
        {
          "name": "securejarhandler-mohist-2.1.11.jar",
          "url": "securejarhandler-mohist-2.1.11.jar",
          "size": 89113,
          "sha512": "383e94595547fb9b5bdece0fe6d4ac434dd06d9b12cbb1e4d68734bc402f6c81abfa6588b1515c53cf45a45d72b637e85b6c0476f0c4eb4cc01ed382ff96731a",
          "sha256": "f4e097e6e9999bf5d7b6730eb847e829e59b3426ed19bed59efc1914c550c29c",
          "sha1": "e05349952ff8e6549a684f291826c834a92fdce7",
          "md5": "347b669d360ad3b5e137ec7d73bb093f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "unsafe",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.3"
          }
        }
      ],
      "files": [
        {
          "name": "securejarhandler-mohist-2.1.11.jar",
          "url": "securejarhandler-mohist-2.1.11.jar",
          "size": 89113,
          "sha512": "383e94595547fb9b5bdece0fe6d4ac434dd06d9b12cbb1e4d68734bc402f6c81abfa6588b1515c53cf45a45d72b637e85b6c0476f0c4eb4cc01ed382ff96731a",
          "sha256": "f4e097e6e9999bf5d7b6730eb847e829e59b3426ed19bed59efc1914c550c29c",
          "sha1": "e05349952ff8e6549a684f291826c834a92fdce7",
          "md5": "347b669d360ad3b5e137ec7d73bb093f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "securejarhandler-mohist-2.1.11-sources.jar",
          "url": "securejarhandler-mohist-2.1.11-sources.jar",
          "size": 31245,
          "sha512": "9910dd47d8b67ca377772a5a509b213c272cdea72775e6832d732f2ce9241da1397ecf136884228202320e4da86a9434c120ffc0ce3f4ec1799fab60e692588f",
          "sha256": "90369b77633f8799ff3ab1440c078365e743b185c91492b5ccc5af7965e00565",
          "sha1": "5bcc1c2d53fe8212b86c90859b70a8171b05690e",
          "md5": "b6b49445074b2715a2b4b2e60d1725c5"
        }
      ]
    }
  ]
}
