{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "brigadier",
    "version": "1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "brigadier-1.20.1.jar",
          "url": "brigadier-1.20.1.jar",
          "size": 79473,
          "sha512": "25131ce4d2c50cd727b20eec637149d9b375ee0ff8bd83e6d16fede7c8aceff4aff08908d9903e11bf7b48cf6481d72af0cec1d0ff0b0da4b0d8e1dd583c5089",
          "sha256": "70dae94f871e888941f97178c0f355c918fcaf89d8a2140ddc964cf6299d3c0d",
          "sha1": "28ba030405f3e15670c3f21e45d7e0fcb50cec0f",
          "md5": "e3e8813a955432f238f04bc9ff8c786f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brigadier-1.20.1.jar",
          "url": "brigadier-1.20.1.jar",
          "size": 79473,
          "sha512": "25131ce4d2c50cd727b20eec637149d9b375ee0ff8bd83e6d16fede7c8aceff4aff08908d9903e11bf7b48cf6481d72af0cec1d0ff0b0da4b0d8e1dd583c5089",
          "sha256": "70dae94f871e888941f97178c0f355c918fcaf89d8a2140ddc964cf6299d3c0d",
          "sha1": "28ba030405f3e15670c3f21e45d7e0fcb50cec0f",
          "md5": "e3e8813a955432f238f04bc9ff8c786f"
        }
      ]
    }
  ]
}
