{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "brigadier",
    "version": "1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "brigadier-1.20.1.jar",
          "url": "brigadier-1.20.1.jar",
          "size": 79415,
          "sha512": "0a8f344a63d67b8682ab7b0b297967cd456f2246f3fe6403848468de915c43530c85fcc0a072c2f647c67cba600afecd6d85b408e3efddb55fecdca2a92c2820",
          "sha256": "4b47b9fda01deb310888fd4538d6c2f33cbc148628b05a2d9b590e2b6bf8a677",
          "sha1": "4fef01150fbc4fd4600dd974a8daffa8262f73d3",
          "md5": "d43ad6ce497519314cbb344a39ae9b7d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brigadier-1.20.1.jar",
          "url": "brigadier-1.20.1.jar",
          "size": 79415,
          "sha512": "0a8f344a63d67b8682ab7b0b297967cd456f2246f3fe6403848468de915c43530c85fcc0a072c2f647c67cba600afecd6d85b408e3efddb55fecdca2a92c2820",
          "sha256": "4b47b9fda01deb310888fd4538d6c2f33cbc148628b05a2d9b590e2b6bf8a677",
          "sha1": "4fef01150fbc4fd4600dd974a8daffa8262f73d3",
          "md5": "d43ad6ce497519314cbb344a39ae9b7d"
        }
      ]
    }
  ]
}
