{
  "formatVersion": "1.1",
  "component": {
    "group": "net.minecrell",
    "module": "terminalconsoleappender",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.26.0"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-reader",
          "version": {
            "requires": "3.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "terminalconsoleappender-1.5.0.jar",
          "url": "terminalconsoleappender-1.5.0.jar",
          "size": 41519,
          "sha512": "044ada0792cfbbebf12ac09eeb541dbb4bd055b48db2aa21bbf101b2a3e27fb57242a6e3a0b57c414bc2fce0ce4a327cb0fc0862752639532f903c09f3265d4b",
          "sha256": "7d46ecbf5b6807dcbcec821986c2554ff6f52696c676e9e049e3cd9b40a9949b",
          "sha1": "e11e081f2fa1c58b55165692bd643a1f7104a65a",
          "md5": "7bd87419505a903cbf88ed30e2e99203"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.26.0"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-reader",
          "version": {
            "requires": "3.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "terminalconsoleappender-1.5.0.jar",
          "url": "terminalconsoleappender-1.5.0.jar",
          "size": 41519,
          "sha512": "044ada0792cfbbebf12ac09eeb541dbb4bd055b48db2aa21bbf101b2a3e27fb57242a6e3a0b57c414bc2fce0ce4a327cb0fc0862752639532f903c09f3265d4b",
          "sha256": "7d46ecbf5b6807dcbcec821986c2554ff6f52696c676e9e049e3cd9b40a9949b",
          "sha1": "e11e081f2fa1c58b55165692bd643a1f7104a65a",
          "md5": "7bd87419505a903cbf88ed30e2e99203"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "terminalconsoleappender-1.5.0-sources.jar",
          "url": "terminalconsoleappender-1.5.0-sources.jar",
          "size": 35908,
          "sha512": "804fb04aac824472b282c2b47a631a12e8e8fe73505ff70262f171c35687b36403f0daf077ff236824431c2549b5a96f61fb9859e0a2faaa5e5ab8af524261e5",
          "sha256": "c10f3d9f6798c20f1b612316575f669527c7c1dd590da2395f5a426f8a69e3ac",
          "sha1": "29d02729995c466cb305451aa689a70334bc25cb",
          "md5": "1bb02e7f8ced43f8f098e2f4ef362e94"
        }
      ]
    }
  ]
}
