{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "mohistdev",
    "version": "1.16.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mohistdev-1.16.5.jar",
          "url": "mohistdev-1.16.5.jar",
          "size": 35408445,
          "sha512": "e8e55e215403dc4d265b86741b9b9fe94cdad041d9c65ed47e495ed345d3afc7772cbcd7b55d971389df9c8995f91b0a2f7098de36f02c9c174391a268355415",
          "sha256": "165b6199ec8b16cab8c400e058ebb51516dba527a32142f091687dcab6c3c290",
          "sha1": "99fff0a76968b6af3156213493e49b56ff67dee9",
          "md5": "f5817f0122dffc30bad98558224f406b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mohistdev-1.16.5.jar",
          "url": "mohistdev-1.16.5.jar",
          "size": 35408445,
          "sha512": "e8e55e215403dc4d265b86741b9b9fe94cdad041d9c65ed47e495ed345d3afc7772cbcd7b55d971389df9c8995f91b0a2f7098de36f02c9c174391a268355415",
          "sha256": "165b6199ec8b16cab8c400e058ebb51516dba527a32142f091687dcab6c3c290",
          "sha1": "99fff0a76968b6af3156213493e49b56ff67dee9",
          "md5": "f5817f0122dffc30bad98558224f406b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mohistdev-1.16.5.jar",
          "url": "mohistdev-1.16.5.jar",
          "size": 35408445,
          "sha512": "e8e55e215403dc4d265b86741b9b9fe94cdad041d9c65ed47e495ed345d3afc7772cbcd7b55d971389df9c8995f91b0a2f7098de36f02c9c174391a268355415",
          "sha256": "165b6199ec8b16cab8c400e058ebb51516dba527a32142f091687dcab6c3c290",
          "sha1": "99fff0a76968b6af3156213493e49b56ff67dee9",
          "md5": "f5817f0122dffc30bad98558224f406b"
        }
      ]
    }
  ]
}
