{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "mohistdev",
    "version": "1.16.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mohistdev-1.16.5.jar",
          "url": "mohistdev-1.16.5.jar",
          "size": 35408445,
          "sha512": "14744f3b7b147b634f3d7c095015eeb6b588681a17d92be8a9ed98b6d37d04b0545a84789ae3d27cceea902c1dfe34289678161e27718dfb0dfc6e549c1affce",
          "sha256": "9db91caea507bab65781402210d95361388f28919e0040a74e3e405e653e80e1",
          "sha1": "2b8e1f60d762306d9c89faad8c6ae027b18ee3c3",
          "md5": "2ebe4392a24deed925d0b6c0f7bc9d25"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "cpw.mods",
          "module": "modlauncher",
          "version": {
            "requires": "8.1.3"
          }
        },
        {
          "group": "cpw.mods",
          "module": "grossjava9hacks",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "accesstransformers",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4-runtime",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "eventbus",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forgespi",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "coremods",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "unsafe",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.jline",
          "module": "jline",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-slf4j18-impl",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "net.minecrell",
          "module": "terminalconsoleappender",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "mixin",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "nashorn-core-compat",
          "version": {
            "requires": "15.1.1.1"
          }
        },
        {
          "group": "commons-lang",
          "module": "commons-lang",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-resolver-provider",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-connector-basic",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-transport-http",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "20.1.0"
          }
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "1.18"
          }
        },
        {
          "group": "jline",
          "module": "jline",
          "version": {
            "requires": "2.14.6"
          }
        },
        {
          "group": "com.googlecode.json-simple",
          "module": "json-simple",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.xerial",
          "module": "sqlite-jdbc",
          "version": {
            "requires": "3.34.0"
          }
        },
        {
          "group": "mysql",
          "module": "mysql-connector-java",
          "version": {
            "requires": "5.1.49"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-iostreams",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "net.md-5",
          "module": "SpecialSource",
          "version": {
            "requires": "1.8.5"
          }
        },
        {
          "group": "net.md-5",
          "module": "bungeecord-chat",
          "version": {
            "requires": "1.16-R0.4"
          }
        }
      ],
      "files": [
        {
          "name": "mohistdev-1.16.5.jar",
          "url": "mohistdev-1.16.5.jar",
          "size": 35408445,
          "sha512": "14744f3b7b147b634f3d7c095015eeb6b588681a17d92be8a9ed98b6d37d04b0545a84789ae3d27cceea902c1dfe34289678161e27718dfb0dfc6e549c1affce",
          "sha256": "9db91caea507bab65781402210d95361388f28919e0040a74e3e405e653e80e1",
          "sha1": "2b8e1f60d762306d9c89faad8c6ae027b18ee3c3",
          "md5": "2ebe4392a24deed925d0b6c0f7bc9d25"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mohistdev-1.16.5.jar",
          "url": "mohistdev-1.16.5.jar",
          "size": 35408445,
          "sha512": "14744f3b7b147b634f3d7c095015eeb6b588681a17d92be8a9ed98b6d37d04b0545a84789ae3d27cceea902c1dfe34289678161e27718dfb0dfc6e549c1affce",
          "sha256": "9db91caea507bab65781402210d95361388f28919e0040a74e3e405e653e80e1",
          "sha1": "2b8e1f60d762306d9c89faad8c6ae027b18ee3c3",
          "md5": "2ebe4392a24deed925d0b6c0f7bc9d25"
        }
      ]
    }
  ]
}
