{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "librariesvault",
    "version": "1.21.1-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "librariesvault-1.21.1-2.jar",
          "url": "librariesvault-1.21.1-2.jar",
          "size": 6402565,
          "sha512": "d433e8044e0bc83dbd742bb9dacedb78e9ad16ae22d90c8d89e54afaf40286846e44f9830709ecc170abe40fdce57f1a216e0e6782fe4f3c4fe2f2ead9142e08",
          "sha256": "6fa3c7bdac33633210fa1f904d0ad67ca7522f98eaf15de6397332ddcd457daf",
          "sha1": "9f1ad6c12854a655804a8e5afb58b4d9d7878fd6",
          "md5": "44dcbb8d43b695224989b364c076b8d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "configurate-yaml",
          "version": {
            "requires": "4.2.0-SNAPSHOT"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.9.6"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-builder-support",
          "version": {
            "requires": "3.9.6"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-model",
          "version": {
            "requires": "3.9.6"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-model-builder",
          "version": {
            "requires": "3.9.6"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-repository-metadata",
          "version": {
            "requires": "3.9.6"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-resolver-provider",
          "version": {
            "requires": "3.9.6"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-api",
          "version": {
            "requires": "1.9.18"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-connector-basic",
          "version": {
            "requires": "1.9.18"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-impl",
          "version": {
            "requires": "1.9.18"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-named-locks",
          "version": {
            "requires": "1.9.18"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-spi",
          "version": {
            "requires": "1.9.18"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-transport-http",
          "version": {
            "requires": "1.9.18"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-util",
          "version": {
            "requires": "1.9.18"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.mariadb.jdbc",
          "module": "mariadb-java-client",
          "version": {
            "requires": "3.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "librariesvault-1.21.1-2.jar",
          "url": "librariesvault-1.21.1-2.jar",
          "size": 6402565,
          "sha512": "d433e8044e0bc83dbd742bb9dacedb78e9ad16ae22d90c8d89e54afaf40286846e44f9830709ecc170abe40fdce57f1a216e0e6782fe4f3c4fe2f2ead9142e08",
          "sha256": "6fa3c7bdac33633210fa1f904d0ad67ca7522f98eaf15de6397332ddcd457daf",
          "sha1": "9f1ad6c12854a655804a8e5afb58b4d9d7878fd6",
          "md5": "44dcbb8d43b695224989b364c076b8d7"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "librariesvault-1.21.1-2.jar",
          "url": "librariesvault-1.21.1-2.jar",
          "size": 6402565,
          "sha512": "d433e8044e0bc83dbd742bb9dacedb78e9ad16ae22d90c8d89e54afaf40286846e44f9830709ecc170abe40fdce57f1a216e0e6782fe4f3c4fe2f2ead9142e08",
          "sha256": "6fa3c7bdac33633210fa1f904d0ad67ca7522f98eaf15de6397332ddcd457daf",
          "sha1": "9f1ad6c12854a655804a8e5afb58b4d9d7878fd6",
          "md5": "44dcbb8d43b695224989b364c076b8d7"
        }
      ]
    }
  ]
}
