server {
    listen 80;
    listen [::]:80;

    server_name {{ current.env.app_url }} www.{{ current.env.app_url }};

    root {{ current.env.app_path }};
    index index.html index.htm index.php;

    location / {
        autoindex on;
        try_files $uri $uri/ =404;
    }

    location /.git {
        deny  all;
    }

    add_header Access-Control-Allow-Origin "*";
}