{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "json",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "json-0.1.jar",
          "url": "json-0.1.jar",
          "size": 134175,
          "sha512": "c44f32842c741e64a19d2d46231ea19297986d5c8c5d0b15e6ce640d5332b9dbc4b89b32a51a9f4dc82076ec3ea43d74d32f4270587b8efe1f7c2dc7cfb07949",
          "sha256": "0593db23db8e1268767ea9324c232657430aa674cb12b7ec11138cbad76635a5",
          "sha1": "4045476970cbcf7d84d9aff50788d058a5c73523",
          "md5": "0c138a81ca7c72858862c11d6b778897"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "json-0.1.jar",
          "url": "json-0.1.jar",
          "size": 134175,
          "sha512": "c44f32842c741e64a19d2d46231ea19297986d5c8c5d0b15e6ce640d5332b9dbc4b89b32a51a9f4dc82076ec3ea43d74d32f4270587b8efe1f7c2dc7cfb07949",
          "sha256": "0593db23db8e1268767ea9324c232657430aa674cb12b7ec11138cbad76635a5",
          "sha1": "4045476970cbcf7d84d9aff50788d058a5c73523",
          "md5": "0c138a81ca7c72858862c11d6b778897"
        }
      ]
    }
  ]
}
