{
  "formatVersion": "1.1",
  "component": {
    "group": "net.neoforged.fancymodloader",
    "module": "earlydisplay",
    "version": "4.0.39-m",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "earlydisplay-4.0.39-m.jar",
          "url": "earlydisplay-4.0.39-m.jar",
          "size": 261721,
          "sha512": "f0ec2dd33c3e1e8494e6be050fd73484ea3a2b7a477489004fefad66b09917b863a7ba905be1b1a82b565090d9020d7653aecee87726bb4b1a159e7ef7bde428",
          "sha256": "57063aba5c19f77c9a0290577c519c3d63ca3743cc72cb5cad30b8be2af1c17e",
          "sha1": "9424a7929b4af18aa9e499fc6ca2bb38dd8653f3",
          "md5": "a6577d3ac9cd9e326b5888f8beb64360"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.neoforged.fancymodloader",
          "module": "loader",
          "version": {
            "requires": "4.0.39-m"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-tinyfd",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "earlydisplay-4.0.39-m.jar",
          "url": "earlydisplay-4.0.39-m.jar",
          "size": 261721,
          "sha512": "f0ec2dd33c3e1e8494e6be050fd73484ea3a2b7a477489004fefad66b09917b863a7ba905be1b1a82b565090d9020d7653aecee87726bb4b1a159e7ef7bde428",
          "sha256": "57063aba5c19f77c9a0290577c519c3d63ca3743cc72cb5cad30b8be2af1c17e",
          "sha1": "9424a7929b4af18aa9e499fc6ca2bb38dd8653f3",
          "md5": "a6577d3ac9cd9e326b5888f8beb64360"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "earlydisplay-4.0.39-m-sources.jar",
          "url": "earlydisplay-4.0.39-m-sources.jar",
          "size": 229984,
          "sha512": "97ccae67ab48b128176c93464cff6deb66a43d1b623221273845937afa507d109281982046cedeaf3d0064f1597334b8cb8d19d85c0ab8b3e25eed7677d347b5",
          "sha256": "50b5b8012c000ddb3cfa7c02a9adb8afe963021e9543d2ae203f02a370d55c0e",
          "sha1": "4f69370de0809c6d861a079971dc3fe9faf4a01e",
          "md5": "cec3ee0a59fd6b27f042868803762b0c"
        }
      ]
    }
  ]
}
