{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc.dynamicenumutil",
    "module": "dynamicenumutil",
    "version": "1.16.5-0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dynamicenumutil-1.16.5-0.1.jar",
          "url": "dynamicenumutil-1.16.5-0.1.jar",
          "size": 6854,
          "sha512": "a133d3c7c6724825cd113d3d9941e52d61a95ec36d064f05607cc448ae241cc82a384c6c59edec59df7b98ac80509a6249d90bd9b5ae4e18ec56c9ff06aa2102",
          "sha256": "22cc84cdeb7bdc6515e158e351654fde7a4c849420eb6660a1c395c0a53dcc75",
          "sha1": "2346bc148c2d5de42bf9f4d570a54a91e6a3c6d7",
          "md5": "c30ac7d037c83554e3c9935e78029308"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dynamicenumutil-1.16.5-0.1.jar",
          "url": "dynamicenumutil-1.16.5-0.1.jar",
          "size": 6854,
          "sha512": "a133d3c7c6724825cd113d3d9941e52d61a95ec36d064f05607cc448ae241cc82a384c6c59edec59df7b98ac80509a6249d90bd9b5ae4e18ec56c9ff06aa2102",
          "sha256": "22cc84cdeb7bdc6515e158e351654fde7a4c849420eb6660a1c395c0a53dcc75",
          "sha1": "2346bc148c2d5de42bf9f4d570a54a91e6a3c6d7",
          "md5": "c30ac7d037c83554e3c9935e78029308"
        }
      ]
    }
  ]
}
