{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "tools",
    "version": "0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tools-0.4.jar",
          "url": "tools-0.4.jar",
          "size": 28415,
          "sha512": "c5bb64de8d416076dda5d0f0884d5e55ecd466fbbee233b8c912a7eaa1e1317c85a15b0505bf375d637b11ba525159111a71196850dccc90f92c6fabe01db393",
          "sha256": "edf8f68906abf2ae28859976ef2270ac2f5cc0c01a566effffeb2aba76e9d7c7",
          "sha1": "354afed459478bee2cd570044d75abb19532fdef",
          "md5": "82e5bf9d32f2b6653cd2ba173229072e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tools-0.4.jar",
          "url": "tools-0.4.jar",
          "size": 28415,
          "sha512": "c5bb64de8d416076dda5d0f0884d5e55ecd466fbbee233b8c912a7eaa1e1317c85a15b0505bf375d637b11ba525159111a71196850dccc90f92c6fabe01db393",
          "sha256": "edf8f68906abf2ae28859976ef2270ac2f5cc0c01a566effffeb2aba76e9d7c7",
          "sha1": "354afed459478bee2cd570044d75abb19532fdef",
          "md5": "82e5bf9d32f2b6653cd2ba173229072e"
        }
      ]
    }
  ]
}
