{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "tools",
    "version": "0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tools-0.4.jar",
          "url": "tools-0.4.jar",
          "size": 28503,
          "sha512": "c668185c49968d06092721cc9ce7002940fa1f4fac2ee864fbca4fc995b763ce6c803a4da2a67f96d8df7ba5ee5b3b98c25dc52b061f754dd659e29c57bc1925",
          "sha256": "725b5e34766890c689609a278e33c9dbbfc9266e26ca6751608eafb102e810a3",
          "sha1": "e897ebd1e12686208d9968a91a1ad2b74c05713d",
          "md5": "b1d7187bcea825be7f3fc27263fa545c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tools-0.4.jar",
          "url": "tools-0.4.jar",
          "size": 28503,
          "sha512": "c668185c49968d06092721cc9ce7002940fa1f4fac2ee864fbca4fc995b763ce6c803a4da2a67f96d8df7ba5ee5b3b98c25dc52b061f754dd659e29c57bc1925",
          "sha256": "725b5e34766890c689609a278e33c9dbbfc9266e26ca6751608eafb102e810a3",
          "sha1": "e897ebd1e12686208d9968a91a1ad2b74c05713d",
          "md5": "b1d7187bcea825be7f3fc27263fa545c"
        }
      ]
    }
  ]
}
