{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "tools",
    "version": "0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tools-0.4.jar",
          "url": "tools-0.4.jar",
          "size": 25366,
          "sha512": "623d980bf8ef876e4478dde213f4adc7fc59328fbc1de38aa595d0b7dff654860c9556b87c0c4ee5ce76aec29fb84e66e6b883d0c78251453a9a5f4a93557e41",
          "sha256": "09736a96002002498e0e800c36bf017280096999cb5e86da638fa6d611678a7e",
          "sha1": "c8c8b0a8c4b1ec7f18fe41ebdb317d3be3dfdecd",
          "md5": "66b1b3c75639c2f46dc28f5999f133fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tools-0.4.jar",
          "url": "tools-0.4.jar",
          "size": 25366,
          "sha512": "623d980bf8ef876e4478dde213f4adc7fc59328fbc1de38aa595d0b7dff654860c9556b87c0c4ee5ce76aec29fb84e66e6b883d0c78251453a9a5f4a93557e41",
          "sha256": "09736a96002002498e0e800c36bf017280096999cb5e86da638fa6d611678a7e",
          "sha1": "c8c8b0a8c4b1ec7f18fe41ebdb317d3be3dfdecd",
          "md5": "66b1b3c75639c2f46dc28f5999f133fe"
        }
      ]
    }
  ]
}
