{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc.remapper",
    "module": "mohistremapper",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mohistremapper-0.3.1.jar",
          "url": "mohistremapper-0.3.1.jar",
          "size": 1887278,
          "sha512": "a6b934bff467053e4cc9086e7aff766720eacd6a05dd22a7a364645988b423d4b4f23bbff5ed8195bb4864097cff69d311bde2159800ce211ade9a5cb3619d6f",
          "sha256": "d3d008eaf9dfba8114368b29ce382d6dd67d49bfc36971fffe9ca91144ace3aa",
          "sha1": "a4fd4f6a5244eac3d9521854372a39589ac79e41",
          "md5": "8ef840da2a7232bb292ae2724adffcf3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "net.md-5",
          "module": "SpecialSource",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "io.izzel",
          "module": "tools",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "cpw.mods",
          "module": "modlauncher",
          "version": {
            "requires": "10.0.8"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "mixin",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "cpw.mods",
          "module": "securejarhandler",
          "version": {
            "requires": "2.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "mohistremapper-0.3.1.jar",
          "url": "mohistremapper-0.3.1.jar",
          "size": 1887278,
          "sha512": "a6b934bff467053e4cc9086e7aff766720eacd6a05dd22a7a364645988b423d4b4f23bbff5ed8195bb4864097cff69d311bde2159800ce211ade9a5cb3619d6f",
          "sha256": "d3d008eaf9dfba8114368b29ce382d6dd67d49bfc36971fffe9ca91144ace3aa",
          "sha1": "a4fd4f6a5244eac3d9521854372a39589ac79e41",
          "md5": "8ef840da2a7232bb292ae2724adffcf3"
        }
      ]
    }
  ]
}
