{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "libraries",
    "version": "0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libraries-0.2.jar",
          "url": "libraries-0.2.jar",
          "size": 6800,
          "sha512": "3422455073ed0f2db74b50c21cc5da98051ea853e7b42ab38f090e485afe75f118a139cf981b253e80c20d919e695c03da50554c7929b0611c04ac210f429e47",
          "sha256": "2fbc52122e5bc08eab51a9b7e6abe8d6ed10b868f2ecfa3aabf6aa4777cdea20",
          "sha1": "76a122b5b5faee61c3ca69ea029be0cae3b182d2",
          "md5": "3ce560542630a83bcfb1ae45b9e7cd05"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mohistmc",
          "module": "tools",
          "version": {
            "requires": "0.4"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "libraries-0.2.jar",
          "url": "libraries-0.2.jar",
          "size": 6800,
          "sha512": "3422455073ed0f2db74b50c21cc5da98051ea853e7b42ab38f090e485afe75f118a139cf981b253e80c20d919e695c03da50554c7929b0611c04ac210f429e47",
          "sha256": "2fbc52122e5bc08eab51a9b7e6abe8d6ed10b868f2ecfa3aabf6aa4777cdea20",
          "sha1": "76a122b5b5faee61c3ca69ea029be0cae3b182d2",
          "md5": "3ce560542630a83bcfb1ae45b9e7cd05"
        }
      ]
    }
  ]
}
