{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "libraries",
    "version": "0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libraries-0.2.jar",
          "url": "libraries-0.2.jar",
          "size": 8135,
          "sha512": "10795dd6d50c80f28df7661c66b0e34198b8bf831f6541b351c7c5353cd1029ab6aba1eee06978043e058db46f0a6686e633f67286b463b0a37cbe26f880a585",
          "sha256": "817c2075e3ce58dbe0697764f1993c25e89fb3a2cdfce3d36bd895ae99ce2ca0",
          "sha1": "5659a901c0b24f01670333addaf8303d84520e51",
          "md5": "12d2642657f0ad9497ef5e8f2ce0beca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mohistmc",
          "module": "tools",
          "version": {
            "requires": "0.4"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "libraries-0.2.jar",
          "url": "libraries-0.2.jar",
          "size": 8135,
          "sha512": "10795dd6d50c80f28df7661c66b0e34198b8bf831f6541b351c7c5353cd1029ab6aba1eee06978043e058db46f0a6686e633f67286b463b0a37cbe26f880a585",
          "sha256": "817c2075e3ce58dbe0697764f1993c25e89fb3a2cdfce3d36bd895ae99ce2ca0",
          "sha1": "5659a901c0b24f01670333addaf8303d84520e51",
          "md5": "12d2642657f0ad9497ef5e8f2ce0beca"
        }
      ]
    }
  ]
}
