{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "json",
    "version": "0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "json-0.4.jar",
          "url": "json-0.4.jar",
          "size": 79491,
          "sha512": "0defa28b2fb3819621664d55b838f9d779cbe459af8b694c499e64fbb5d6fe219cb4f256a5245f5be77c2379da5bd21300149310ab4bb4f5393a61fc8377f6e0",
          "sha256": "28131727c5edcd041749cadb1b1b6674dd0717b4254e2a6423d8ff934955326e",
          "sha1": "7748023a37003f2bc3384042f7265622c45fcae5",
          "md5": "ae4f7516d37317569f602525a50417ef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "json-0.4.jar",
          "url": "json-0.4.jar",
          "size": 79491,
          "sha512": "0defa28b2fb3819621664d55b838f9d779cbe459af8b694c499e64fbb5d6fe219cb4f256a5245f5be77c2379da5bd21300149310ab4bb4f5393a61fc8377f6e0",
          "sha256": "28131727c5edcd041749cadb1b1b6674dd0717b4254e2a6423d8ff934955326e",
          "sha1": "7748023a37003f2bc3384042f7265622c45fcae5",
          "md5": "ae4f7516d37317569f602525a50417ef"
        }
      ]
    }
  ]
}
