{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "json",
    "version": "0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "json-0.4.jar",
          "url": "json-0.4.jar",
          "size": 79618,
          "sha512": "20db32f8c6ee88e3a2d66f12893aee903ea64dcb62b77f92d447bde16d0ab65dc036a834a85eaeb69dfcdbf261ed5a749598e0a0de6169f63882c87a58301e0f",
          "sha256": "f56c5bcedd94390d16d1fd8602c16ce9587e52b9c086e6935a7ab497b0c3c027",
          "sha1": "163169459d2b32d07de4c9dbca74ceb38db62e64",
          "md5": "b99f19ac7342b7b2ea846aac6cc6638c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "json-0.4.jar",
          "url": "json-0.4.jar",
          "size": 79618,
          "sha512": "20db32f8c6ee88e3a2d66f12893aee903ea64dcb62b77f92d447bde16d0ab65dc036a834a85eaeb69dfcdbf261ed5a749598e0a0de6169f63882c87a58301e0f",
          "sha256": "f56c5bcedd94390d16d1fd8602c16ce9587e52b9c086e6935a7ab497b0c3c027",
          "sha1": "163169459d2b32d07de4c9dbca74ceb38db62e64",
          "md5": "b99f19ac7342b7b2ea846aac6cc6638c"
        }
      ]
    }
  ]
}
