{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "i18n",
    "version": "0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "i18n-0.7.jar",
          "url": "i18n-0.7.jar",
          "size": 3742,
          "sha512": "6d6c44c4ef383b6021559d2adc1fb055cf2904f0e9e97d988dd1e36f9bcd8c823d3015e32db1d83a75e3504b1c7c4b0a93686453043db1c97c9ebe9c54722225",
          "sha256": "1e4d762f3754f7b362b55705c98d23ff2ab16efc9a37d7054b17e40a96aa2970",
          "sha1": "f309f13834c3e67ca8856de5c950c8e6a42874d1",
          "md5": "536bb7f497b34899a0b8c79d6b314bbb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "i18n-0.7.jar",
          "url": "i18n-0.7.jar",
          "size": 3742,
          "sha512": "6d6c44c4ef383b6021559d2adc1fb055cf2904f0e9e97d988dd1e36f9bcd8c823d3015e32db1d83a75e3504b1c7c4b0a93686453043db1c97c9ebe9c54722225",
          "sha256": "1e4d762f3754f7b362b55705c98d23ff2ab16efc9a37d7054b17e40a96aa2970",
          "sha1": "f309f13834c3e67ca8856de5c950c8e6a42874d1",
          "md5": "536bb7f497b34899a0b8c79d6b314bbb"
        }
      ]
    }
  ]
}
