{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "libraries",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libraries-0.1.jar",
          "url": "libraries-0.1.jar",
          "size": 7122,
          "sha512": "0ba0ebaf9c1b704370625f9786322fd203edf165a7304fc680eafdb5a16c3efd72e7d1c273bce389b4cb8af1906eb371c572c238a1b3615581d36a394c65850b",
          "sha256": "b9abd57d6b4a98b18e2869a4088aee41a640934e3d3bfcc348b476c2ed5338fb",
          "sha1": "0079e5c2ac533caf6d3cf53193a24390f725ac90",
          "md5": "8ef0706e86e20e41bf6c24b2acf696cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mohistmc",
          "module": "tools",
          "version": {
            "requires": "0.4"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "libraries-0.1.jar",
          "url": "libraries-0.1.jar",
          "size": 7122,
          "sha512": "0ba0ebaf9c1b704370625f9786322fd203edf165a7304fc680eafdb5a16c3efd72e7d1c273bce389b4cb8af1906eb371c572c238a1b3615581d36a394c65850b",
          "sha256": "b9abd57d6b4a98b18e2869a4088aee41a640934e3d3bfcc348b476c2ed5338fb",
          "sha1": "0079e5c2ac533caf6d3cf53193a24390f725ac90",
          "md5": "8ef0706e86e20e41bf6c24b2acf696cd"
        }
      ]
    }
  ]
}
