{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "libraries",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libraries-0.1.jar",
          "url": "libraries-0.1.jar",
          "size": 8135,
          "sha512": "f247c5cc5a6c9ea88d6e8844a69e173b8419b2fcd70c8d522153eeab89c06cb208d6e18904ef39325222b1b66858aa1a3a5abb93c25a7f1449d974a9cfa585e5",
          "sha256": "a279dc295f54ee6106644265656edd3fb455cb2e043caeec74900207ac324050",
          "sha1": "91d8e1f21620508cb0d5e91c346aef07d3a98b4a",
          "md5": "7cbf52ebd6970ee6b21bbae5ee754533"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mohistmc",
          "module": "tools",
          "version": {
            "requires": "0.4"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "libraries-0.1.jar",
          "url": "libraries-0.1.jar",
          "size": 8135,
          "sha512": "f247c5cc5a6c9ea88d6e8844a69e173b8419b2fcd70c8d522153eeab89c06cb208d6e18904ef39325222b1b66858aa1a3a5abb93c25a7f1449d974a9cfa585e5",
          "sha256": "a279dc295f54ee6106644265656edd3fb455cb2e043caeec74900207ac324050",
          "sha1": "91d8e1f21620508cb0d5e91c346aef07d3a98b4a",
          "md5": "7cbf52ebd6970ee6b21bbae5ee754533"
        }
      ]
    }
  ]
}
