{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc.dynamicenumutil",
    "module": "DynamicEnumUtil",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "DynamicEnumUtil-0.1.jar",
          "url": "DynamicEnumUtil-0.1.jar",
          "size": 6405,
          "sha512": "04fd970c60fa30eac1715ca50e1c5244cc0280449a74e90c2210f114a5ebdc89922df7658dec16157cc79e09d3d384eaa4b3798e5187325eccb41e6630a26233",
          "sha256": "7fc773e4ea9a4d200c2419ead4e80522d846eb2157cc0df0eda8ebffc92aa393",
          "sha1": "d37002b4e0e9f88e208bfc3b97c75872a1926a75",
          "md5": "0e4fea832b5b897fdd19305f63599da1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DynamicEnumUtil-0.1.jar",
          "url": "DynamicEnumUtil-0.1.jar",
          "size": 6405,
          "sha512": "04fd970c60fa30eac1715ca50e1c5244cc0280449a74e90c2210f114a5ebdc89922df7658dec16157cc79e09d3d384eaa4b3798e5187325eccb41e6630a26233",
          "sha256": "7fc773e4ea9a4d200c2419ead4e80522d846eb2157cc0df0eda8ebffc92aa393",
          "sha1": "d37002b4e0e9f88e208bfc3b97c75872a1926a75",
          "md5": "0e4fea832b5b897fdd19305f63599da1"
        }
      ]
    }
  ]
}
