services:
  app:
    image: mohistmc-maven-${ENV}:${VERSION}
    build:
      context: ../..
      dockerfile: Dockerfile.app
    container_name: mohistmc_maven_${ENV}
    restart: always
    volumes:
      - /var/www/maven:/var/www/maven