{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "mohistdev",
    "version": "1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mohistdev-1.20.1.jar",
          "url": "mohistdev-1.20.1.jar",
          "size": 102552061,
          "sha512": "c0d331d0f57414fdc3d72df4fa3655f8c301835cb79399a142e30c219d897dfe65c4302946b53c0b4466c9e8c817939cb674b3c4e78a71ca261e1d903211f152",
          "sha256": "2351c1a87a1c2dc653a58c88eb69ff8afea3c6f7a8f347ceb5824d0f861b640a",
          "sha1": "df303cf49be0caab9440d17c4cf3d7af9961c436",
          "md5": "229156dda95b5d3e6d064a753e6de037"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mohistdev-1.20.1.jar",
          "url": "mohistdev-1.20.1.jar",
          "size": 102552061,
          "sha512": "c0d331d0f57414fdc3d72df4fa3655f8c301835cb79399a142e30c219d897dfe65c4302946b53c0b4466c9e8c817939cb674b3c4e78a71ca261e1d903211f152",
          "sha256": "2351c1a87a1c2dc653a58c88eb69ff8afea3c6f7a8f347ceb5824d0f861b640a",
          "sha1": "df303cf49be0caab9440d17c4cf3d7af9961c436",
          "md5": "229156dda95b5d3e6d064a753e6de037"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mohistdev-1.20.1.jar",
          "url": "mohistdev-1.20.1.jar",
          "size": 102552061,
          "sha512": "c0d331d0f57414fdc3d72df4fa3655f8c301835cb79399a142e30c219d897dfe65c4302946b53c0b4466c9e8c817939cb674b3c4e78a71ca261e1d903211f152",
          "sha256": "2351c1a87a1c2dc653a58c88eb69ff8afea3c6f7a8f347ceb5824d0f861b640a",
          "sha1": "df303cf49be0caab9440d17c4cf3d7af9961c436",
          "md5": "229156dda95b5d3e6d064a753e6de037"
        }
      ]
    }
  ]
}
