{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "mohistdev",
    "version": "1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mohistdev-1.20.1.jar",
          "url": "mohistdev-1.20.1.jar",
          "size": 102552178,
          "sha512": "ef72abb534dfc51f407114ebb1022527d9e831da2d5eddfb82167c20cab60a079b634867b9075b1223e82bf203b71c02b39d4ad6a4d9dd4b6dafe600c7d78cce",
          "sha256": "88556e69ffede9a59b42f940e8e92ec9ad4c00a9d5f38606e185dc4f5225feb9",
          "sha1": "048faea4772ea742b6c6e1df65c2d709e7bcd5b3",
          "md5": "9b1ddfdb9a43c9c33bbd18eadbc0686f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mohistdev-1.20.1.jar",
          "url": "mohistdev-1.20.1.jar",
          "size": 102552178,
          "sha512": "ef72abb534dfc51f407114ebb1022527d9e831da2d5eddfb82167c20cab60a079b634867b9075b1223e82bf203b71c02b39d4ad6a4d9dd4b6dafe600c7d78cce",
          "sha256": "88556e69ffede9a59b42f940e8e92ec9ad4c00a9d5f38606e185dc4f5225feb9",
          "sha1": "048faea4772ea742b6c6e1df65c2d709e7bcd5b3",
          "md5": "9b1ddfdb9a43c9c33bbd18eadbc0686f"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mohistdev-1.20.1.jar",
          "url": "mohistdev-1.20.1.jar",
          "size": 102552178,
          "sha512": "ef72abb534dfc51f407114ebb1022527d9e831da2d5eddfb82167c20cab60a079b634867b9075b1223e82bf203b71c02b39d4ad6a4d9dd4b6dafe600c7d78cce",
          "sha256": "88556e69ffede9a59b42f940e8e92ec9ad4c00a9d5f38606e185dc4f5225feb9",
          "sha1": "048faea4772ea742b6c6e1df65c2d709e7bcd5b3",
          "md5": "9b1ddfdb9a43c9c33bbd18eadbc0686f"
        }
      ]
    }
  ]
}
