{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "remap",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "remap-0.1.jar",
          "url": "remap-0.1.jar",
          "size": 52704,
          "sha512": "158402ac888e2ffee278a9309a3025a0b40f2c420f3f1d2f3463f7a6d5fa85e146a9ce9a477e4386e707e76bdc7ecb1087784bd9600e4893bfeb261d10161b35",
          "sha256": "31acd70b373d6afe81f40c729d16a2bd3d4d3d977035a4a27d85597b59297422",
          "sha1": "222a6d3f5cddf89c41f3470f2ce63d0a176deff2",
          "md5": "3d0477d9b1b0457ba93cb0bc69ec7309"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        },
        {
          "group": "com.mohistmc",
          "module": "dynamicenum",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "net.md-5",
          "module": "SpecialSource",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "remap-0.1.jar",
          "url": "remap-0.1.jar",
          "size": 52704,
          "sha512": "158402ac888e2ffee278a9309a3025a0b40f2c420f3f1d2f3463f7a6d5fa85e146a9ce9a477e4386e707e76bdc7ecb1087784bd9600e4893bfeb261d10161b35",
          "sha256": "31acd70b373d6afe81f40c729d16a2bd3d4d3d977035a4a27d85597b59297422",
          "sha1": "222a6d3f5cddf89c41f3470f2ce63d0a176deff2",
          "md5": "3d0477d9b1b0457ba93cb0bc69ec7309"
        }
      ]
    }
  ]
}
