{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mojang",
    "module": "brigadier",
    "version": "mohist-1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "brigadier-mohist-1.20.1.jar",
          "url": "brigadier-mohist-1.20.1.jar",
          "size": 79543,
          "sha512": "bdc666419959e0ec348cfbd27c9a42c95e1a53cb657c26ca32d7b4b80b6398d1f790bdffb34cd8510c6166e17ce04431dc79fb4e4c38f560b065831b3b8c81c5",
          "sha256": "3ab525b5501b1bccaecc47fe34aeacb466b4cd6ae45432a713908a2591224aa8",
          "sha1": "6dd91ba2d71c78b3113a3248b79fac500f210805",
          "md5": "c24d6084546d76c0aec6169a8c6acd62"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brigadier-mohist-1.20.1.jar",
          "url": "brigadier-mohist-1.20.1.jar",
          "size": 79543,
          "sha512": "bdc666419959e0ec348cfbd27c9a42c95e1a53cb657c26ca32d7b4b80b6398d1f790bdffb34cd8510c6166e17ce04431dc79fb4e4c38f560b065831b3b8c81c5",
          "sha256": "3ab525b5501b1bccaecc47fe34aeacb466b4cd6ae45432a713908a2591224aa8",
          "sha1": "6dd91ba2d71c78b3113a3248b79fac500f210805",
          "md5": "c24d6084546d76c0aec6169a8c6acd62"
        }
      ]
    }
  ]
}
