{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc.gradle",
    "module": "ForgeGradle",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ForgeGradle-1.0.jar",
          "url": "ForgeGradle-1.0.jar",
          "size": 454037,
          "sha512": "8681dc960a7cb3cd1ceac0e9e418dfc406fbf8e0993fb789c1b5c214145eb01a387551192f0c67e8d6559dd654de1fe32e9d890c9200a20e8831ea55af30d17e",
          "sha256": "a257abfee8fc7de2985bc3c40a0460ac45bed6322e13c08ecec8c587015dd853",
          "sha1": "62086b6f691828d30d833336869c3152eb852157",
          "md5": "b502e6e093eb0a4794644cefcf0827b8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "unsafe",
          "version": {
            "requires": "0.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.6.3"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.13"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.4.13"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "DiffPatch",
          "version": {
            "requires": "2.0.7"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "DiffPatch",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.3.17"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.3.17"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ForgeGradle-1.0.jar",
          "url": "ForgeGradle-1.0.jar",
          "size": 454037,
          "sha512": "8681dc960a7cb3cd1ceac0e9e418dfc406fbf8e0993fb789c1b5c214145eb01a387551192f0c67e8d6559dd654de1fe32e9d890c9200a20e8831ea55af30d17e",
          "sha256": "a257abfee8fc7de2985bc3c40a0460ac45bed6322e13c08ecec8c587015dd853",
          "sha1": "62086b6f691828d30d833336869c3152eb852157",
          "md5": "b502e6e093eb0a4794644cefcf0827b8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ForgeGradle-1.0-sources.jar",
          "url": "ForgeGradle-1.0-sources.jar",
          "size": 239210,
          "sha512": "14cd6577d7cc94dfe806ed1790ec832f765907c3e58868aa16e4aa9769ba45c8491859fb6ffc0ca53e6dde6e3ab414b36d64769b81af5a086e8539fd49d47e9c",
          "sha256": "7d7927864f5558e2d0183f164f96c02aaf87eece9301665c08fe5640cf9273c2",
          "sha1": "448c3b04ea9d0d56ffb68e424c9ce66ab24ec92b",
          "md5": "93bbdf404c57fefecb1e26382db0a2ef"
        }
      ]
    }
  ]
}
