{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc.gradle",
    "module": "ForgeGradle",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ForgeGradle-1.0.jar",
          "url": "ForgeGradle-1.0.jar",
          "size": 454037,
          "sha512": "80d4f9070a4f05e8ccc34e96f76e8e00f870f528b81f9d7233edea901ced0321bb0649ed25697a0c94596e4f1eb3bbed4f12c511f6057f82f60d9bd92c02b80a",
          "sha256": "b9e63be526504994df963ad6557fac669ffa5fd9fcd1a3531cca44d03b7f2578",
          "sha1": "ad5dfafb6ccd7f892f2191557bb857964779575e",
          "md5": "4629b814abf545c7eb76e3b2adf536ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.mohistmc",
          "module": "artifactural",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "unsafe",
          "version": {
            "requires": "0.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.6.3"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.13"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.4.13"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "DiffPatch",
          "version": {
            "requires": "2.0.7"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "DiffPatch",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.3.17"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.3.17"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ForgeGradle-1.0.jar",
          "url": "ForgeGradle-1.0.jar",
          "size": 454037,
          "sha512": "80d4f9070a4f05e8ccc34e96f76e8e00f870f528b81f9d7233edea901ced0321bb0649ed25697a0c94596e4f1eb3bbed4f12c511f6057f82f60d9bd92c02b80a",
          "sha256": "b9e63be526504994df963ad6557fac669ffa5fd9fcd1a3531cca44d03b7f2578",
          "sha1": "ad5dfafb6ccd7f892f2191557bb857964779575e",
          "md5": "4629b814abf545c7eb76e3b2adf536ca"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ForgeGradle-1.0-sources.jar",
          "url": "ForgeGradle-1.0-sources.jar",
          "size": 239210,
          "sha512": "b5192a3ad532ed519a455de8cb21f6f2f9ed13a9cd2c55d328468acf9a0329132b3073d9880c8a9adb378040bdbf8d54c9aa3d9cb1e0ceb09d75d80d993aeecb",
          "sha256": "43802501f9b8886b2f1a19ff50b4d6702222544615ba981dff1e8b5f3d4808a3",
          "sha1": "6c679860114f23fe68636bdf1c4802a53f53a6be",
          "md5": "12a967810b2d6441a34deef3df692652"
        }
      ]
    }
  ]
}
