{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc.gradle",
    "module": "ForgeGradle",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ForgeGradle-1.0.jar",
          "url": "ForgeGradle-1.0.jar",
          "size": 458346,
          "sha512": "b588882e12fdf4e352a2c899870e909674a80ad38084b5b046acc753448fa676587b8d85373908224aef223c11f95186c8aebbdca1f63fdcd5812fec6b760a14",
          "sha256": "841f356974494a805c943310d3345cd0dbd209a436dc31a7e94b8c7970fceab8",
          "sha1": "dd94d149cfbdb95da45437e6025de8e797f3278e",
          "md5": "9e5f364fb3c521ea270046727949c9cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.mohistmc",
          "module": "artifactural",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "unsafe",
          "version": {
            "requires": "0.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.6.3"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.13"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.4.13"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "DiffPatch",
          "version": {
            "requires": "2.0.7"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "DiffPatch",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.3.17"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.3.17"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ForgeGradle-1.0.jar",
          "url": "ForgeGradle-1.0.jar",
          "size": 458346,
          "sha512": "b588882e12fdf4e352a2c899870e909674a80ad38084b5b046acc753448fa676587b8d85373908224aef223c11f95186c8aebbdca1f63fdcd5812fec6b760a14",
          "sha256": "841f356974494a805c943310d3345cd0dbd209a436dc31a7e94b8c7970fceab8",
          "sha1": "dd94d149cfbdb95da45437e6025de8e797f3278e",
          "md5": "9e5f364fb3c521ea270046727949c9cd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ForgeGradle-1.0-sources.jar",
          "url": "ForgeGradle-1.0-sources.jar",
          "size": 244108,
          "sha512": "001923c616ac9e9f5218553d072caa5d2c7b117d4529e2efce9c0f6bc46b2c234ae8b53354bf4b4c0f03190fcd19d8cb2dbe028ec26fa39ebeb3ae22d616b1fb",
          "sha256": "d3ddd116383d934fadd1e41cc1a2e4e11f7eb8af3a61ed840973a9c98826d571",
          "sha1": "16c648fc9440c1393ada339fffbe3ea70f5c54ee",
          "md5": "ab2aa58512c96c8cfdbbc537b35bc0ca"
        }
      ]
    }
  ]
}
