{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "librariesvault",
    "version": "1.21.1-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "librariesvault-1.21.1-1.jar",
          "url": "librariesvault-1.21.1-1.jar",
          "size": 1146348,
          "sha512": "b36374f9330f42389abcda8e831354e1db3d79bc058bcb9768586b17dfae4dea2f1450ce6dd9353427705ce59caf7d20e952c317ac1def70052c3ddf3e8e5357",
          "sha256": "b9afb98d95cffbc405a1a14d93224b9b72b6bab27771588c4452dda23a05e89d",
          "sha1": "95f62238eca893c4ee5e8b4406d7dc77ff49ca0e",
          "md5": "eedc88e3978f1abab368c13b828ccb5e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "configurate-yaml",
          "version": {
            "requires": "4.2.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "librariesvault-1.21.1-1.jar",
          "url": "librariesvault-1.21.1-1.jar",
          "size": 1146348,
          "sha512": "b36374f9330f42389abcda8e831354e1db3d79bc058bcb9768586b17dfae4dea2f1450ce6dd9353427705ce59caf7d20e952c317ac1def70052c3ddf3e8e5357",
          "sha256": "b9afb98d95cffbc405a1a14d93224b9b72b6bab27771588c4452dda23a05e89d",
          "sha1": "95f62238eca893c4ee5e8b4406d7dc77ff49ca0e",
          "md5": "eedc88e3978f1abab368c13b828ccb5e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "librariesvault-1.21.1-1.jar",
          "url": "librariesvault-1.21.1-1.jar",
          "size": 1146348,
          "sha512": "b36374f9330f42389abcda8e831354e1db3d79bc058bcb9768586b17dfae4dea2f1450ce6dd9353427705ce59caf7d20e952c317ac1def70052c3ddf3e8e5357",
          "sha256": "b9afb98d95cffbc405a1a14d93224b9b72b6bab27771588c4452dda23a05e89d",
          "sha1": "95f62238eca893c4ee5e8b4406d7dc77ff49ca0e",
          "md5": "eedc88e3978f1abab368c13b828ccb5e"
        }
      ]
    }
  ]
}
