{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "librariesvault",
    "version": "1.21.1-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "librariesvault-1.21.1-1.jar",
          "url": "librariesvault-1.21.1-1.jar",
          "size": 3531365,
          "sha512": "3671bcc9958d9aa230a544079221064d3569ed09b3f8840cb375200a09426d32c93363afc3cfd23a86be906662f9c18c0313bb441fd562a93d2915c96ac11c3a",
          "sha256": "8c9d615965c498613130229e7ff3ea5cda16d66897b57d4783ded91d949720fd",
          "sha1": "c623cdcb9941038c188285a172dedce20f61aaa0",
          "md5": "194a9beeb32de1c2605655ab2476f54e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "configurate-yaml",
          "version": {
            "requires": "4.2.0-SNAPSHOT"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.9.6"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-builder-support",
          "version": {
            "requires": "3.9.6"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-model",
          "version": {
            "requires": "3.9.6"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-model-builder",
          "version": {
            "requires": "3.9.6"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-repository-metadata",
          "version": {
            "requires": "3.9.6"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-resolver-provider",
          "version": {
            "requires": "3.9.6"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-api",
          "version": {
            "requires": "1.9.18"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-connector-basic",
          "version": {
            "requires": "1.9.18"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-impl",
          "version": {
            "requires": "1.9.18"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-named-locks",
          "version": {
            "requires": "1.9.18"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-spi",
          "version": {
            "requires": "1.9.18"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-transport-http",
          "version": {
            "requires": "1.9.18"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-util",
          "version": {
            "requires": "1.9.18"
          }
        }
      ],
      "files": [
        {
          "name": "librariesvault-1.21.1-1.jar",
          "url": "librariesvault-1.21.1-1.jar",
          "size": 3531365,
          "sha512": "3671bcc9958d9aa230a544079221064d3569ed09b3f8840cb375200a09426d32c93363afc3cfd23a86be906662f9c18c0313bb441fd562a93d2915c96ac11c3a",
          "sha256": "8c9d615965c498613130229e7ff3ea5cda16d66897b57d4783ded91d949720fd",
          "sha1": "c623cdcb9941038c188285a172dedce20f61aaa0",
          "md5": "194a9beeb32de1c2605655ab2476f54e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "librariesvault-1.21.1-1.jar",
          "url": "librariesvault-1.21.1-1.jar",
          "size": 3531365,
          "sha512": "3671bcc9958d9aa230a544079221064d3569ed09b3f8840cb375200a09426d32c93363afc3cfd23a86be906662f9c18c0313bb441fd562a93d2915c96ac11c3a",
          "sha256": "8c9d615965c498613130229e7ff3ea5cda16d66897b57d4783ded91d949720fd",
          "sha1": "c623cdcb9941038c188285a172dedce20f61aaa0",
          "md5": "194a9beeb32de1c2605655ab2476f54e"
        }
      ]
    }
  ]
}
