{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mojang",
    "module": "brigadier",
    "version": "mohist-1.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "brigadier-mohist-1.12.1.jar",
          "url": "brigadier-mohist-1.12.1.jar",
          "size": 79543,
          "sha512": "502b92ea93294756fa6df482813993486ed4fe4fd3b683f5f02969a056788eb4e5f8e36e52a03a1b80db59acdb70058885c66c913b9d24fe440c2b9b49bcda91",
          "sha256": "81f241a8a7f1cc8cf6af8d71fbc0ff948d2ecf540c067bcf2e7c7ceac392c484",
          "sha1": "8aa246dfe2d185167536f40530704457249cc678",
          "md5": "3e5dfd4d2475ef08dd9a9fb1b609ca56"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brigadier-mohist-1.12.1.jar",
          "url": "brigadier-mohist-1.12.1.jar",
          "size": 79543,
          "sha512": "502b92ea93294756fa6df482813993486ed4fe4fd3b683f5f02969a056788eb4e5f8e36e52a03a1b80db59acdb70058885c66c913b9d24fe440c2b9b49bcda91",
          "sha256": "81f241a8a7f1cc8cf6af8d71fbc0ff948d2ecf540c067bcf2e7c7ceac392c484",
          "sha1": "8aa246dfe2d185167536f40530704457249cc678",
          "md5": "3e5dfd4d2475ef08dd9a9fb1b609ca56"
        }
      ]
    }
  ]
}
