{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc.fancymodloader",
    "module": "junit-fml",
    "version": "4.0.40",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "junit-fml-4.0.40.jar",
          "url": "junit-fml-4.0.40.jar",
          "size": 3719,
          "sha512": "70c2febe7943fa4114b6d924cafe01124263b56e96ad466bfb423f26a138142407432ef35139e5406a1fc907b74ec4348ee0809a6a0af2872486580e4d0c911e",
          "sha256": "e966e16fd58d22ecfdb0c72e4c005ecc5f69933eae8fc0efb379e180f92a9958",
          "sha1": "d7582728ba3e3a84988021e40a2943bc20eadea1",
          "md5": "4ab85bc9d09aac437b3a8ed591ec9d2c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        }
      ],
      "files": [
        {
          "name": "junit-fml-4.0.40.jar",
          "url": "junit-fml-4.0.40.jar",
          "size": 3719,
          "sha512": "70c2febe7943fa4114b6d924cafe01124263b56e96ad466bfb423f26a138142407432ef35139e5406a1fc907b74ec4348ee0809a6a0af2872486580e4d0c911e",
          "sha256": "e966e16fd58d22ecfdb0c72e4c005ecc5f69933eae8fc0efb379e180f92a9958",
          "sha1": "d7582728ba3e3a84988021e40a2943bc20eadea1",
          "md5": "4ab85bc9d09aac437b3a8ed591ec9d2c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-fml-4.0.40-sources.jar",
          "url": "junit-fml-4.0.40-sources.jar",
          "size": 2949,
          "sha512": "a0415250f94b8e7269225a313aba97ef74ab689588c63ed3a1cc47cd8043aaa1b80ad81bd389e84432bc99147c2b9c7ba9960322e84f9c2f25a5cb9aed468f56",
          "sha256": "91a9de691686fdac2554006d1b6e227f57f016b01e30c5eb827978121efcae43",
          "sha1": "328e5d645641d49e9b984026aafa2cfb5cf3e0d5",
          "md5": "81a5790b888c26334a739da9f6015437"
        }
      ]
    }
  ]
}
