{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc.fancymodloader",
    "module": "junit-fml",
    "version": "4.0.40",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "junit-fml-4.0.40.jar",
          "url": "junit-fml-4.0.40.jar",
          "size": 3721,
          "sha512": "a018d8f6731938eece4ce76330ddfcae0bd4bf8d74c58718f7562bcfff5c3ebd686463c3f54232261414d138f0a0be4124d7c0b1a701eac3e9ce3b9f690ff191",
          "sha256": "e3228910b85a4fb57fc79d7048bb991ab9312551ff86c1db834332e6085f37c6",
          "sha1": "44b272366d4f8b8f4b49366fd52833541193625d",
          "md5": "98c5953675711fb4e43281ea754791cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        }
      ],
      "files": [
        {
          "name": "junit-fml-4.0.40.jar",
          "url": "junit-fml-4.0.40.jar",
          "size": 3721,
          "sha512": "a018d8f6731938eece4ce76330ddfcae0bd4bf8d74c58718f7562bcfff5c3ebd686463c3f54232261414d138f0a0be4124d7c0b1a701eac3e9ce3b9f690ff191",
          "sha256": "e3228910b85a4fb57fc79d7048bb991ab9312551ff86c1db834332e6085f37c6",
          "sha1": "44b272366d4f8b8f4b49366fd52833541193625d",
          "md5": "98c5953675711fb4e43281ea754791cd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-fml-4.0.40-sources.jar",
          "url": "junit-fml-4.0.40-sources.jar",
          "size": 2949,
          "sha512": "a0415250f94b8e7269225a313aba97ef74ab689588c63ed3a1cc47cd8043aaa1b80ad81bd389e84432bc99147c2b9c7ba9960322e84f9c2f25a5cb9aed468f56",
          "sha256": "91a9de691686fdac2554006d1b6e227f57f016b01e30c5eb827978121efcae43",
          "sha1": "328e5d645641d49e9b984026aafa2cfb5cf3e0d5",
          "md5": "81a5790b888c26334a739da9f6015437"
        }
      ]
    }
  ]
}
