{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "mohistdev",
    "version": "1.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mohistdev-1.20.2.jar",
          "url": "mohistdev-1.20.2.jar",
          "size": 104385320,
          "sha512": "4d9b37fc255efc0389618c926c9109230e263f93d0f442f789da22397019357811bcefb6e1e17f46a45ce9be0fdfbda0d13cae47d569b28c61d8eaf21e4b6122",
          "sha256": "f832937ab20e7b3ff01222a80563617683648093e0b7b0098945e70fe2a2a059",
          "sha1": "86a345a000b5e41fd0e482ed263c1f55ffc9d172",
          "md5": "93526c742fd9c9c620691aa642690381"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "securemodules",
          "version": {
            "requires": "2.2.3-mohist"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "accesstransformers",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4-runtime",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "eventbus",
          "version": {
            "requires": "6.0.5"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forgespi",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "coremods",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "modlauncher",
          "version": {
            "requires": "10.1.1"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "unsafe",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "mergetool",
          "version": {
            "requires": "1.1.5"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "mergetool",
              "type": "jar",
              "extension": "jar",
              "classifier": "api"
            }
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.4"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.4"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "net.minecrell",
          "module": "terminalconsoleappender",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-reader",
          "version": {
            "requires": "3.21.0"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-terminal",
          "version": {
            "requires": "3.21.0"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-terminal-jansi",
          "version": {
            "requires": "3.21.0"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "mixin",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.openjdk.nashorn",
          "module": "nashorn-core",
          "version": {
            "requires": "15.3"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.3.19"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.3.19"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.8.5"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-builder-support",
          "version": {
            "requires": "3.8.5"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-model",
          "version": {
            "requires": "3.8.5"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-model-builder",
          "version": {
            "requires": "3.8.5"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-repository-metadata",
          "version": {
            "requires": "3.8.5"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-resolver-provider",
          "version": {
            "requires": "3.8.5"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-api",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-connector-basic",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-impl",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-spi",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-transport-http",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-util",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.eclipse.sisu",
          "module": "org.eclipse.sisu.inject",
          "version": {
            "requires": "0.3.5"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "1.18"
          }
        },
        {
          "group": "jline",
          "module": "jline",
          "version": {
            "requires": "2.14.6"
          }
        },
        {
          "group": "com.googlecode.json-simple",
          "module": "json-simple",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.xerial",
          "module": "sqlite-jdbc",
          "version": {
            "requires": "3.42.0.1"
          }
        },
        {
          "group": "com.mysql",
          "module": "mysql-connector-j",
          "version": {
            "requires": "8.1.0"
          }
        },
        {
          "group": "net.md-5",
          "module": "SpecialSource",
          "version": {
            "requires": "1.11.2"
          }
        },
        {
          "group": "net.md-5",
          "module": "bungeecord-chat",
          "version": {
            "requires": "1.20-R0.1"
          }
        },
        {
          "group": "io.izzel",
          "module": "tools",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.mohistmc",
          "module": "dynamicenum",
          "version": {
            "requires": "0.3"
          }
        },
        {
          "group": "com.mohistmc",
          "module": "i18n",
          "version": {
            "requires": "0.6"
          }
        },
        {
          "group": "com.mohistmc",
          "module": "tools",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.mohistmc",
          "module": "json",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "failureaccess",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "com.mojang",
          "module": "authlib",
          "version": {
            "requires": "5.0.47"
          }
        },
        {
          "group": "com.mojang",
          "module": "logging",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "commons-lang",
          "module": "commons-lang",
          "version": {
            "requires": "2.6-mohist"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-iostreams",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-slf4j2-impl",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.13.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.13.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.12"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.mojang",
          "module": "javabridge",
          "version": {
            "requires": "2.0.25"
          }
        },
        {
          "group": "com.mojang",
          "module": "datafixerupper",
          "version": {
            "requires": "6.0.8"
          }
        },
        {
          "group": "com.mojang",
          "module": "brigadier",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "com.github.oshi",
          "module": "oshi-core",
          "version": {
            "requires": "6.4.0"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.97.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-codec",
          "version": {
            "requires": "4.1.97.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-common",
          "version": {
            "requires": "4.1.97.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-handler",
          "version": {
            "requires": "4.1.97.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-resolver",
          "version": {
            "requires": "4.1.97.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport",
          "version": {
            "requires": "4.1.97.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport-classes-epoll",
          "version": {
            "requires": "4.1.97.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport-native-unix-common",
          "version": {
            "requires": "4.1.97.Final"
          }
        }
      ],
      "files": [
        {
          "name": "mohistdev-1.20.2.jar",
          "url": "mohistdev-1.20.2.jar",
          "size": 104385320,
          "sha512": "4d9b37fc255efc0389618c926c9109230e263f93d0f442f789da22397019357811bcefb6e1e17f46a45ce9be0fdfbda0d13cae47d569b28c61d8eaf21e4b6122",
          "sha256": "f832937ab20e7b3ff01222a80563617683648093e0b7b0098945e70fe2a2a059",
          "sha1": "86a345a000b5e41fd0e482ed263c1f55ffc9d172",
          "md5": "93526c742fd9c9c620691aa642690381"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mohistdev-1.20.2.jar",
          "url": "mohistdev-1.20.2.jar",
          "size": 104385320,
          "sha512": "4d9b37fc255efc0389618c926c9109230e263f93d0f442f789da22397019357811bcefb6e1e17f46a45ce9be0fdfbda0d13cae47d569b28c61d8eaf21e4b6122",
          "sha256": "f832937ab20e7b3ff01222a80563617683648093e0b7b0098945e70fe2a2a059",
          "sha1": "86a345a000b5e41fd0e482ed263c1f55ffc9d172",
          "md5": "93526c742fd9c9c620691aa642690381"
        }
      ]
    }
  ]
}
