{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "librariesvault",
    "version": "1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "librariesvault-1.21.1.jar",
          "url": "librariesvault-1.21.1.jar",
          "size": 2150748,
          "sha512": "f56020f2e9cfab0570aa11080f355859ddb5a78cdcb709b5c7a8100779039cc9cb538f4325714309a93901aeae875d7e8f650211dca552b31619c9bd454ea50b",
          "sha256": "c680cee8b1a37088042100c14e27d661e0ad155c1b1ba9df4b93db14152c2212",
          "sha1": "9dc22b77065bbb76a7f4c675f33941d409b2d200",
          "md5": "02d629c9eefce0dd65d8c215f08cca9d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "librariesvault-1.21.1.jar",
          "url": "librariesvault-1.21.1.jar",
          "size": 2150748,
          "sha512": "f56020f2e9cfab0570aa11080f355859ddb5a78cdcb709b5c7a8100779039cc9cb538f4325714309a93901aeae875d7e8f650211dca552b31619c9bd454ea50b",
          "sha256": "c680cee8b1a37088042100c14e27d661e0ad155c1b1ba9df4b93db14152c2212",
          "sha1": "9dc22b77065bbb76a7f4c675f33941d409b2d200",
          "md5": "02d629c9eefce0dd65d8c215f08cca9d"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "librariesvault-1.21.1.jar",
          "url": "librariesvault-1.21.1.jar",
          "size": 2150748,
          "sha512": "f56020f2e9cfab0570aa11080f355859ddb5a78cdcb709b5c7a8100779039cc9cb538f4325714309a93901aeae875d7e8f650211dca552b31619c9bd454ea50b",
          "sha256": "c680cee8b1a37088042100c14e27d661e0ad155c1b1ba9df4b93db14152c2212",
          "sha1": "9dc22b77065bbb76a7f4c675f33941d409b2d200",
          "md5": "02d629c9eefce0dd65d8c215f08cca9d"
        }
      ]
    }
  ]
}
