{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "librariesvault",
    "version": "1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "librariesvault-1.21.1.jar",
          "url": "librariesvault-1.21.1.jar",
          "size": 2286030,
          "sha512": "00e64afb48e171bf0cccdb6411b4b43d0f7eb097eb2c6a26e52907f4efc2c3aa96c6df094088780cfa64daccf7e946f8e9c3857dad20e3a01f56e21d6135148b",
          "sha256": "1376b6477499238843130e05505f19b99db600987eae6d2b699142d52346eb2f",
          "sha1": "c7db59f28fea72b3b6a7a1525a4ef70338036a3c",
          "md5": "0ffce19e803eb2d9a4b27de1887e5daf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "librariesvault-1.21.1.jar",
          "url": "librariesvault-1.21.1.jar",
          "size": 2286030,
          "sha512": "00e64afb48e171bf0cccdb6411b4b43d0f7eb097eb2c6a26e52907f4efc2c3aa96c6df094088780cfa64daccf7e946f8e9c3857dad20e3a01f56e21d6135148b",
          "sha256": "1376b6477499238843130e05505f19b99db600987eae6d2b699142d52346eb2f",
          "sha1": "c7db59f28fea72b3b6a7a1525a4ef70338036a3c",
          "md5": "0ffce19e803eb2d9a4b27de1887e5daf"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "librariesvault-1.21.1.jar",
          "url": "librariesvault-1.21.1.jar",
          "size": 2286030,
          "sha512": "00e64afb48e171bf0cccdb6411b4b43d0f7eb097eb2c6a26e52907f4efc2c3aa96c6df094088780cfa64daccf7e946f8e9c3857dad20e3a01f56e21d6135148b",
          "sha256": "1376b6477499238843130e05505f19b99db600987eae6d2b699142d52346eb2f",
          "sha1": "c7db59f28fea72b3b6a7a1525a4ef70338036a3c",
          "md5": "0ffce19e803eb2d9a4b27de1887e5daf"
        }
      ]
    }
  ]
}
