{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "librariesvault",
    "version": "1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "librariesvault-1.21.1.jar",
          "url": "librariesvault-1.21.1.jar",
          "size": 1937629,
          "sha512": "2398adee78a367b0ba2402201fa75a27a1794d3df55e0c57198cf3cae44355826081ca6f61329c01550fb0e24321ee70f7cdb6f005ef648c4b3c6cc68da150f9",
          "sha256": "29be9caa1223e6dee386298644dd566c944daa7f00f764a0ba81126f1779bb22",
          "sha1": "6c0563500ce507987aaa36c3f3bcfd4bef72af3d",
          "md5": "db4c03ebbd861cdf160ea135b0605831"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "librariesvault-1.21.1.jar",
          "url": "librariesvault-1.21.1.jar",
          "size": 1937629,
          "sha512": "2398adee78a367b0ba2402201fa75a27a1794d3df55e0c57198cf3cae44355826081ca6f61329c01550fb0e24321ee70f7cdb6f005ef648c4b3c6cc68da150f9",
          "sha256": "29be9caa1223e6dee386298644dd566c944daa7f00f764a0ba81126f1779bb22",
          "sha1": "6c0563500ce507987aaa36c3f3bcfd4bef72af3d",
          "md5": "db4c03ebbd861cdf160ea135b0605831"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "librariesvault-1.21.1.jar",
          "url": "librariesvault-1.21.1.jar",
          "size": 1937629,
          "sha512": "2398adee78a367b0ba2402201fa75a27a1794d3df55e0c57198cf3cae44355826081ca6f61329c01550fb0e24321ee70f7cdb6f005ef648c4b3c6cc68da150f9",
          "sha256": "29be9caa1223e6dee386298644dd566c944daa7f00f764a0ba81126f1779bb22",
          "sha1": "6c0563500ce507987aaa36c3f3bcfd4bef72af3d",
          "md5": "db4c03ebbd861cdf160ea135b0605831"
        }
      ]
    }
  ]
}
