{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc.yaml",
    "module": "yaml",
    "version": "0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "yaml-0.4.jar",
          "url": "yaml-0.4.jar",
          "size": 39439,
          "sha512": "0f6d96c1e364ac0ddf7ca6bd9c4a35c256ea061d62f0ffae79ebdf72193b16d1d570424568fd8bc57fc199e8860cfcee231e29b4349df4577194dee7d9019273",
          "sha256": "f8dca2f7617b25b5b351546c6e79d4c29f49433635f0ac14d4e3d9f325ecf207",
          "sha1": "54b7a526d946125a5f56ddb68f6b51539ced64f6",
          "md5": "a6944e8daa02cce4f4462afe66d40de1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "yaml-0.4.jar",
          "url": "yaml-0.4.jar",
          "size": 39439,
          "sha512": "0f6d96c1e364ac0ddf7ca6bd9c4a35c256ea061d62f0ffae79ebdf72193b16d1d570424568fd8bc57fc199e8860cfcee231e29b4349df4577194dee7d9019273",
          "sha256": "f8dca2f7617b25b5b351546c6e79d4c29f49433635f0ac14d4e3d9f325ecf207",
          "sha1": "54b7a526d946125a5f56ddb68f6b51539ced64f6",
          "md5": "a6944e8daa02cce4f4462afe66d40de1"
        }
      ]
    }
  ]
}
