{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "forgespi",
    "version": "6.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "forgespi-6.0.0.jar",
          "url": "forgespi-6.0.0.jar",
          "size": 32711,
          "sha512": "68bfffb61b0542d3610cf5c93373acc8b80874a17ca8ed12f256a9bc17cfa0423c84ca6bf40d6ff93c9456bd8b2d8686539b3a95aca0394d7b3367bef84c3c0d",
          "sha256": "a2e6aaad12ddb3e50c817b4e2d3aaf342bbf11877f6a7fdf0b4bfaca68616189",
          "sha1": "9f20688244999e6e5a6171ee1ed92dbc2602f360",
          "md5": "33847316e38800e01a3927a688633535"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "cpw.mods",
          "module": "modlauncher",
          "version": {
            "requires": "9.0.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "cpw.mods",
          "module": "securejarhandler",
          "version": {
            "requires": "0.9.52"
          }
        }
      ],
      "files": [
        {
          "name": "forgespi-6.0.0.jar",
          "url": "forgespi-6.0.0.jar",
          "size": 32711,
          "sha512": "68bfffb61b0542d3610cf5c93373acc8b80874a17ca8ed12f256a9bc17cfa0423c84ca6bf40d6ff93c9456bd8b2d8686539b3a95aca0394d7b3367bef84c3c0d",
          "sha256": "a2e6aaad12ddb3e50c817b4e2d3aaf342bbf11877f6a7fdf0b4bfaca68616189",
          "sha1": "9f20688244999e6e5a6171ee1ed92dbc2602f360",
          "md5": "33847316e38800e01a3927a688633535"
        }
      ]
    }
  ]
}
