{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc.miraimbot",
    "module": "compiler",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "c6nslpohu5ahhdacmlhzqr6h3a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.20"
          }
        },
        {
          "group": "com.mohistmc.yaml",
          "module": "Yaml",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.mohistmc.miraimbot",
          "module": "annotations",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.75"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20-RC"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.4.2.jar",
          "url": "compiler-0.4.2.jar",
          "size": 1290938,
          "sha512": "d8650d578ea89b35554685e427ab0f46533c2b093ef02a7ebd7ef99d14dd8b4603046f789104f8ae9cd60fcfc20402518cdd2c5f6a9ef2e97fbfec1d9475ebb3",
          "sha256": "f5eff1bb8eaba836391e7fdc635a2b8ee03a93e46eb388a3a8ea0d5e5f11d3bb",
          "sha1": "f601a5b16400c684a3a3e00461f356403c4506ea",
          "md5": "e3f66d0503db0eba0de16db92416ad63"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.20"
          }
        },
        {
          "group": "com.mohistmc.yaml",
          "module": "Yaml",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.mohistmc.miraimbot",
          "module": "annotations",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.75"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20-RC"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.4.2.jar",
          "url": "compiler-0.4.2.jar",
          "size": 1290938,
          "sha512": "d8650d578ea89b35554685e427ab0f46533c2b093ef02a7ebd7ef99d14dd8b4603046f789104f8ae9cd60fcfc20402518cdd2c5f6a9ef2e97fbfec1d9475ebb3",
          "sha256": "f5eff1bb8eaba836391e7fdc635a2b8ee03a93e46eb388a3a8ea0d5e5f11d3bb",
          "sha1": "f601a5b16400c684a3a3e00461f356403c4506ea",
          "md5": "e3f66d0503db0eba0de16db92416ad63"
        }
      ]
    }
  ]
}
