{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc.fancymodloader",
    "module": "loader",
    "version": "4.0.39",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "net.neoforged",
          "module": "mergetool",
          "version": {
            "requires": "2.0.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "mergetool",
              "type": "jar",
              "extension": "jar",
              "classifier": "api"
            }
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.22.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.8.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "cpw.mods",
          "module": "modlauncher",
          "version": {
            "requires": "11.0.3"
          }
        },
        {
          "group": "net.neoforged",
          "module": "coremods",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "com.mojang",
          "module": "logging",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "net.neoforged",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.neoforged",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.neoforged",
          "module": "bus",
          "version": {
            "requires": "8.0.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.mohistmc.fancymodloader",
          "module": "junit-fml",
          "version": {
            "requires": "4.0.39"
          }
        }
      ],
      "files": [
        {
          "name": "loader-4.0.39.jar",
          "url": "loader-4.0.39.jar",
          "size": 504789,
          "sha512": "dceb0a759c50db3b7355eb18a2e4a590d9f87aa25895acc92d4bfdb9a71c88b55157f36e0b0d9d45a98b0c82b242d063620a5393de8e935b5c3c333af98cdcd4",
          "sha256": "fadb098b22e4e983206a46ecb56e9a3ec4f954124cc16629d9d84ec9fb33c49f",
          "sha1": "6ade74035a5a79d09ec2c6985943b83fdcfb1f8f",
          "md5": "514721b7a2ebb0818f560ef85b9b2cec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.neoforged",
          "module": "JarJarFileSystems",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "cpw.mods",
          "module": "securejarhandler",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "net.neoforged",
          "module": "accesstransformers",
          "version": {
            "requires": "10.0.1"
          }
        },
        {
          "group": "net.neoforged.accesstransformers",
          "module": "at-modlauncher",
          "version": {
            "requires": "10.0.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "modlauncher"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "sponge-mixin",
          "version": {
            "requires": "0.14.0+mixin.0.8.6"
          }
        },
        {
          "group": "net.minecrell",
          "module": "terminalconsoleappender",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.22.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "net.neoforged",
          "module": "mergetool",
          "version": {
            "requires": "2.0.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "mergetool",
              "type": "jar",
              "extension": "jar",
              "classifier": "api"
            }
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.22.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.8.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "cpw.mods",
          "module": "modlauncher",
          "version": {
            "requires": "11.0.3"
          }
        },
        {
          "group": "net.neoforged",
          "module": "coremods",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "com.mojang",
          "module": "logging",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "net.neoforged",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.neoforged",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.neoforged",
          "module": "bus",
          "version": {
            "requires": "8.0.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.mohistmc.fancymodloader",
          "module": "junit-fml",
          "version": {
            "requires": "4.0.39"
          }
        }
      ],
      "files": [
        {
          "name": "loader-4.0.39.jar",
          "url": "loader-4.0.39.jar",
          "size": 504789,
          "sha512": "dceb0a759c50db3b7355eb18a2e4a590d9f87aa25895acc92d4bfdb9a71c88b55157f36e0b0d9d45a98b0c82b242d063620a5393de8e935b5c3c333af98cdcd4",
          "sha256": "fadb098b22e4e983206a46ecb56e9a3ec4f954124cc16629d9d84ec9fb33c49f",
          "sha1": "6ade74035a5a79d09ec2c6985943b83fdcfb1f8f",
          "md5": "514721b7a2ebb0818f560ef85b9b2cec"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "loader-4.0.39-sources.jar",
          "url": "loader-4.0.39-sources.jar",
          "size": 275971,
          "sha512": "0306945fb3ae81be91a4e652c8ee31b448fb589e88ac6bf5da1aecd6bb77bde33e6b7ed50f0ae023185976ec9e4212ece07f913c05f83a470c02463472eedd4f",
          "sha256": "3affd907fa3fc21e6656c409e206097b5ee96a0ecde5ef18ea66c23960b61985",
          "sha1": "12f04f41037d01f2dbda4d15e31b310dc02e725a",
          "md5": "8c335ee1e097e32cb8618448dbf83094"
        }
      ]
    }
  ]
}
