{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "i18n",
    "version": "0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "i18n-0.2.jar",
          "url": "i18n-0.2.jar",
          "size": 2516,
          "sha512": "cb9aced24b00dc7e0a84c5bd064872fc3feb53afe6ff8dbe7421d1c2336aa9de9cdf2488294661d934cae9967b269de8ca2ac8219eb12593655d3d8f757d1d80",
          "sha256": "371ab58ff84c2bb4f08e35e59c557ba84c97710c009f519d8784fc935a4a414e",
          "sha1": "35bca13806165104f7494db86e6f621184f6c487",
          "md5": "956a8d30a6e464eef86027fb74fd7177"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "i18n-0.2.jar",
          "url": "i18n-0.2.jar",
          "size": 2516,
          "sha512": "cb9aced24b00dc7e0a84c5bd064872fc3feb53afe6ff8dbe7421d1c2336aa9de9cdf2488294661d934cae9967b269de8ca2ac8219eb12593655d3d8f757d1d80",
          "sha256": "371ab58ff84c2bb4f08e35e59c557ba84c97710c009f519d8784fc935a4a414e",
          "sha1": "35bca13806165104f7494db86e6f621184f6c487",
          "md5": "956a8d30a6e464eef86027fb74fd7177"
        }
      ]
    }
  ]
}
