{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "i18n",
    "version": "0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "i18n-0.2.jar",
          "url": "i18n-0.2.jar",
          "size": 2664,
          "sha512": "06caf6b63ef5ffb1f14cb256551ff7d5e7cdc621dad9306dfb86c28d0deb9a3b9ba04cc8525336d3036641d1b0588f85bf36997b588156099b55ec1b486d4c6f",
          "sha256": "5bb920c60374d77321c5936f8fd46ac03e54a21b3f115b4379a20d49b6db1d03",
          "sha1": "8a4f2119bb44143ed09e1943b015e5512d170965",
          "md5": "cd9251cab2c7fda3c03497defdc0048c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "i18n-0.2.jar",
          "url": "i18n-0.2.jar",
          "size": 2664,
          "sha512": "06caf6b63ef5ffb1f14cb256551ff7d5e7cdc621dad9306dfb86c28d0deb9a3b9ba04cc8525336d3036641d1b0588f85bf36997b588156099b55ec1b486d4c6f",
          "sha256": "5bb920c60374d77321c5936f8fd46ac03e54a21b3f115b4379a20d49b6db1d03",
          "sha1": "8a4f2119bb44143ed09e1943b015e5512d170965",
          "md5": "cd9251cab2c7fda3c03497defdc0048c"
        }
      ]
    }
  ]
}
