{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "i18n",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "i18n-0.1.jar",
          "url": "i18n-0.1.jar",
          "size": 2695,
          "sha512": "ddae4b0be35b74c253b7b839ea0c8d2f45eef9081c970a62f41fc4d7675f9de36f0569a18b061c05e1c8a806d45b029c0db8546fb1101206a36ff319ded064d8",
          "sha256": "e08d089db0f9653bb2d2b6c7424835e31f8c3473a90d8189e7ca35e79442adcb",
          "sha1": "16201e778a18362db86311da69b3f794c70d0427",
          "md5": "012e81b705b91aeb7d94bb2790ae0c7a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "i18n-0.1.jar",
          "url": "i18n-0.1.jar",
          "size": 2695,
          "sha512": "ddae4b0be35b74c253b7b839ea0c8d2f45eef9081c970a62f41fc4d7675f9de36f0569a18b061c05e1c8a806d45b029c0db8546fb1101206a36ff319ded064d8",
          "sha256": "e08d089db0f9653bb2d2b6c7424835e31f8c3473a90d8189e7ca35e79442adcb",
          "sha1": "16201e778a18362db86311da69b3f794c70d0427",
          "md5": "012e81b705b91aeb7d94bb2790ae0c7a"
        }
      ]
    }
  ]
}
