{
  "formatVersion": "1.1",
  "component": {
    "group": "net.neoforged.fancymodloader",
    "module": "junit-fml",
    "version": "4.0.39-m",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "junit-fml-4.0.39-m.jar",
          "url": "junit-fml-4.0.39-m.jar",
          "size": 3724,
          "sha512": "76ffa52f46bbf09e9f4ed53d45e4242b5849d61a8738054d101b44a6fafdd5aa7ddecb43120c44cf366cb59342010190278ffb41d61b943c5822ea578e0f1eed",
          "sha256": "b040c0f627ff6fa929df0e3a6da82211d54700184fa98d6f97f508b45248d56b",
          "sha1": "c243e84063fb874bef643bb7ef291d099f852d67",
          "md5": "814548931c54e792aae2f7430d87ffaa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        }
      ],
      "files": [
        {
          "name": "junit-fml-4.0.39-m.jar",
          "url": "junit-fml-4.0.39-m.jar",
          "size": 3724,
          "sha512": "76ffa52f46bbf09e9f4ed53d45e4242b5849d61a8738054d101b44a6fafdd5aa7ddecb43120c44cf366cb59342010190278ffb41d61b943c5822ea578e0f1eed",
          "sha256": "b040c0f627ff6fa929df0e3a6da82211d54700184fa98d6f97f508b45248d56b",
          "sha1": "c243e84063fb874bef643bb7ef291d099f852d67",
          "md5": "814548931c54e792aae2f7430d87ffaa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-fml-4.0.39-m-sources.jar",
          "url": "junit-fml-4.0.39-m-sources.jar",
          "size": 2949,
          "sha512": "0b616a448a93dc9a6925dd435222841fe2f4b606d2ca785e0634fe4946893352f895a72ae635aab753e5498bd203e07c1e5c02f434a2713979889a139f70555e",
          "sha256": "c2083b0a3d1c994dc9689fac1e03111a1aa9f146a9390644a8d1702484e49ba1",
          "sha1": "30082355ca7dd98ec2b49324a0c9c19840b6b689",
          "md5": "6220713b92d683ac58969216821e4010"
        }
      ]
    }
  ]
}
