{
  "formatVersion": "1.1",
  "component": {
    "group": "net.neoforged.fancymodloader",
    "module": "junit-fml",
    "version": "4.0.39-m",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "junit-fml-4.0.39-m.jar",
          "url": "junit-fml-4.0.39-m.jar",
          "size": 3723,
          "sha512": "662b237533849e062f799af7c4e1da943c323031ba6ef48cc50b04ea37cac21ab548fffea8d6654309245c50032e6e5c048952f2de3a3a9f47dd6ff52a5cb3ed",
          "sha256": "5e43d2e9e8f23252f310c0955fdbd0cf7c7c17e53aabac1f2f9b8dde9cd08829",
          "sha1": "de9f82d66d14853a8acd5f71dca311e1b2b1b3f0",
          "md5": "e710163e96c9b86b73170f1b9de043b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        }
      ],
      "files": [
        {
          "name": "junit-fml-4.0.39-m.jar",
          "url": "junit-fml-4.0.39-m.jar",
          "size": 3723,
          "sha512": "662b237533849e062f799af7c4e1da943c323031ba6ef48cc50b04ea37cac21ab548fffea8d6654309245c50032e6e5c048952f2de3a3a9f47dd6ff52a5cb3ed",
          "sha256": "5e43d2e9e8f23252f310c0955fdbd0cf7c7c17e53aabac1f2f9b8dde9cd08829",
          "sha1": "de9f82d66d14853a8acd5f71dca311e1b2b1b3f0",
          "md5": "e710163e96c9b86b73170f1b9de043b4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-fml-4.0.39-m-sources.jar",
          "url": "junit-fml-4.0.39-m-sources.jar",
          "size": 2949,
          "sha512": "0b616a448a93dc9a6925dd435222841fe2f4b606d2ca785e0634fe4946893352f895a72ae635aab753e5498bd203e07c1e5c02f434a2713979889a139f70555e",
          "sha256": "c2083b0a3d1c994dc9689fac1e03111a1aa9f146a9390644a8d1702484e49ba1",
          "sha1": "30082355ca7dd98ec2b49324a0c9c19840b6b689",
          "md5": "6220713b92d683ac58969216821e4010"
        }
      ]
    }
  ]
}
