{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc.yaml",
    "module": "yaml",
    "version": "0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "yaml-0.2.jar",
          "url": "yaml-0.2.jar",
          "size": 34550,
          "sha512": "206993d341be970ac4f46623dea62b4b20b3094277800c050db9f1bf60939b58434c9fdd4f98a60c05cf10986c4d565e4ddfb127f3040210dcc83c42cf404cef",
          "sha256": "a18786d16422d85b240af4e8cf0a35596dde8cb081fe3440211a8ef4429e8788",
          "sha1": "c5e9e78de36c0c32f06ef6f3e21b8f6369b14db8",
          "md5": "0cac2f8464639d645abe4575a28d543a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.30"
          }
        }
      ],
      "files": [
        {
          "name": "yaml-0.2.jar",
          "url": "yaml-0.2.jar",
          "size": 34550,
          "sha512": "206993d341be970ac4f46623dea62b4b20b3094277800c050db9f1bf60939b58434c9fdd4f98a60c05cf10986c4d565e4ddfb127f3040210dcc83c42cf404cef",
          "sha256": "a18786d16422d85b240af4e8cf0a35596dde8cb081fe3440211a8ef4429e8788",
          "sha1": "c5e9e78de36c0c32f06ef6f3e21b8f6369b14db8",
          "md5": "0cac2f8464639d645abe4575a28d543a"
        }
      ]
    }
  ]
}
