{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc.yaml",
    "module": "yaml",
    "version": "0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "yaml-0.2.jar",
          "url": "yaml-0.2.jar",
          "size": 34341,
          "sha512": "aba72e0a84ae0020485e6f4a01d54a3bf512dc28a6b20ddd129a5e35958bc1d139dccb25746d476f2946b152bbd08c0f7e11c7c337121eaf5df792ea571c3ac6",
          "sha256": "b17babb43585f3b70895edadf8bd83f53283cd46471d6248d50193e96cca3cdc",
          "sha1": "96801fd96b460d2faaa55fa61fc8d94e217dd193",
          "md5": "f62bccafe11c877414de8a17bb8cc5df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.30"
          }
        }
      ],
      "files": [
        {
          "name": "yaml-0.2.jar",
          "url": "yaml-0.2.jar",
          "size": 34341,
          "sha512": "aba72e0a84ae0020485e6f4a01d54a3bf512dc28a6b20ddd129a5e35958bc1d139dccb25746d476f2946b152bbd08c0f7e11c7c337121eaf5df792ea571c3ac6",
          "sha256": "b17babb43585f3b70895edadf8bd83f53283cd46471d6248d50193e96cca3cdc",
          "sha1": "96801fd96b460d2faaa55fa61fc8d94e217dd193",
          "md5": "f62bccafe11c877414de8a17bb8cc5df"
        }
      ]
    }
  ]
}
