{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "libraries",
    "version": "0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libraries-0.3.jar",
          "url": "libraries-0.3.jar",
          "size": 7340,
          "sha512": "46bcd40676e92faa89235ca1312f9744b8f472a7de73e7a334ba3fb5f4c5229b4420d52aec1737b43d45163687023ad0fc6d15b5a4353388ff4c58736088223b",
          "sha256": "8e7be820028fbb44c4d61b3d01f82dcf97d23c78d9f68b991f50b38e885340c3",
          "sha1": "de137805eae176e1d699dcda48fb1b2dfd0e23be",
          "md5": "5d7443602b767ff615f2e929465ed5f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mohistmc",
          "module": "tools",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "libraries-0.3.jar",
          "url": "libraries-0.3.jar",
          "size": 7340,
          "sha512": "46bcd40676e92faa89235ca1312f9744b8f472a7de73e7a334ba3fb5f4c5229b4420d52aec1737b43d45163687023ad0fc6d15b5a4353388ff4c58736088223b",
          "sha256": "8e7be820028fbb44c4d61b3d01f82dcf97d23c78d9f68b991f50b38e885340c3",
          "sha1": "de137805eae176e1d699dcda48fb1b2dfd0e23be",
          "md5": "5d7443602b767ff615f2e929465ed5f9"
        }
      ]
    }
  ]
}
