{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc.remapper",
    "module": "mohistremapper",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mohistremapper-0.1.jar",
          "url": "mohistremapper-0.1.jar",
          "size": 695075,
          "sha512": "7f1ec38a32c614835d39f8340490cfb6ef5cbbf2c0936d99176adc3fcafdf14044a82543f97d02262796e573a48376a2cb714f13c6f80aae74a984464303ed4e",
          "sha256": "2cefd3482ba79184423276c4d5efc12100465ed597dbfd08c0697f46210de9c3",
          "sha1": "8f18ecbb3222d073c5eb44a147fd39da92ddbaf2",
          "md5": "7068c75aef5e987156b97d49cc3ead25"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "21.0"
          }
        },
        {
          "group": "net.md-5",
          "module": "SpecialSource",
          "version": {
            "requires": "1.8.5"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "io.izzel",
          "module": "tools",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "cpw.mods",
          "module": "modlauncher",
          "version": {
            "requires": "10.0.8"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "mixin",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "cpw.mods",
          "module": "securejarhandler",
          "version": {
            "requires": "2.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "mohistremapper-0.1.jar",
          "url": "mohistremapper-0.1.jar",
          "size": 695075,
          "sha512": "7f1ec38a32c614835d39f8340490cfb6ef5cbbf2c0936d99176adc3fcafdf14044a82543f97d02262796e573a48376a2cb714f13c6f80aae74a984464303ed4e",
          "sha256": "2cefd3482ba79184423276c4d5efc12100465ed597dbfd08c0697f46210de9c3",
          "sha1": "8f18ecbb3222d073c5eb44a147fd39da92ddbaf2",
          "md5": "7068c75aef5e987156b97d49cc3ead25"
        }
      ]
    }
  ]
}
