{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc.remapper",
    "module": "mohistremapper",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mohistremapper-0.1.jar",
          "url": "mohistremapper-0.1.jar",
          "size": 82246,
          "sha512": "afed5c509df40096eaa81cf54774cca2a5b7d138fdd0152d28122461a22c59b29f5ef05246303bd4679437f159153db6b000cf88f767f6aa397efe287cf81596",
          "sha256": "0691bb27350b20c2c0b6c4e9e6045b59e6316aee901d9226ee7abb63b8e752bc",
          "sha1": "62f36971454b3f1617aa54594762e76e5544720b",
          "md5": "a331955b4ee6994ac8c25f057eb77e15"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "21.0"
          }
        },
        {
          "group": "net.md-5",
          "module": "SpecialSource",
          "version": {
            "requires": "1.8.5"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "io.izzel",
          "module": "tools",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "cpw.mods",
          "module": "modlauncher",
          "version": {
            "requires": "10.0.8"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "mixin",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "cpw.mods",
          "module": "securejarhandler",
          "version": {
            "requires": "2.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "mohistremapper-0.1.jar",
          "url": "mohistremapper-0.1.jar",
          "size": 82246,
          "sha512": "afed5c509df40096eaa81cf54774cca2a5b7d138fdd0152d28122461a22c59b29f5ef05246303bd4679437f159153db6b000cf88f767f6aa397efe287cf81596",
          "sha256": "0691bb27350b20c2c0b6c4e9e6045b59e6316aee901d9226ee7abb63b8e752bc",
          "sha1": "62f36971454b3f1617aa54594762e76e5544720b",
          "md5": "a331955b4ee6994ac8c25f057eb77e15"
        }
      ]
    }
  ]
}
