{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "dynamicenum",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dynamicenum-0.1.jar",
          "url": "dynamicenum-0.1.jar",
          "size": 4587,
          "sha512": "24713489b8162e3fd86a52a2884c56c1fc444f77ea8da18265b62075c8a435ce085f8269b1db1546d199d9e7553aa137b8c439b14dd40c1342d6f51e2df28d23",
          "sha256": "a78b2eed9af52899ada8236be287c1ce5987244a07d54badcfb02f995d0c9301",
          "sha1": "893eb553c6b5e3ce308bca1805516cfe3fbbef56",
          "md5": "ae876076bdcc7ee5673b445c313d3be5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dynamicenum-0.1.jar",
          "url": "dynamicenum-0.1.jar",
          "size": 4587,
          "sha512": "24713489b8162e3fd86a52a2884c56c1fc444f77ea8da18265b62075c8a435ce085f8269b1db1546d199d9e7553aa137b8c439b14dd40c1342d6f51e2df28d23",
          "sha256": "a78b2eed9af52899ada8236be287c1ce5987244a07d54badcfb02f995d0c9301",
          "sha1": "893eb553c6b5e3ce308bca1805516cfe3fbbef56",
          "md5": "ae876076bdcc7ee5673b445c313d3be5"
        }
      ]
    }
  ]
}
