{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "json",
    "version": "0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "json-0.3.jar",
          "url": "json-0.3.jar",
          "size": 147595,
          "sha512": "4939687cafd21cd25c979134a45a642d0c69e285b9fa09651761d88668f5508eed3078ae59c0388d832af771f13aacd7e60470efa8f015e4184ef606760f0419",
          "sha256": "172293d13aa0976d0aa90196235e4a7a56c3b106f0e01ae861d767e385d86549",
          "sha1": "218705ae0048443cdd3c7a51c7d2dfc029e018b3",
          "md5": "69f4f157d28384709036d19eab8fd45c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "json-0.3.jar",
          "url": "json-0.3.jar",
          "size": 147595,
          "sha512": "4939687cafd21cd25c979134a45a642d0c69e285b9fa09651761d88668f5508eed3078ae59c0388d832af771f13aacd7e60470efa8f015e4184ef606760f0419",
          "sha256": "172293d13aa0976d0aa90196235e4a7a56c3b106f0e01ae861d767e385d86549",
          "sha1": "218705ae0048443cdd3c7a51c7d2dfc029e018b3",
          "md5": "69f4f157d28384709036d19eab8fd45c"
        }
      ]
    }
  ]
}
