{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "tools",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tools-0.5.1.jar",
          "url": "tools-0.5.1.jar",
          "size": 28993,
          "sha512": "22244c572d6315535c2762058336b7f8edb619936f02bc5089a5b9463e7d26b92919cf437a9aad8364c2ef57b80ceff97ead435976270fee69181a7344eec9b6",
          "sha256": "2445c9899cb92d88598a5699506393cbfd4c049bf901d87d26731459e07e9710",
          "sha1": "99129be12d0b026632b0d9b5402927a8b75ac744",
          "md5": "fabc608b832218bf52f43e523a16e536"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tools-0.5.1.jar",
          "url": "tools-0.5.1.jar",
          "size": 28993,
          "sha512": "22244c572d6315535c2762058336b7f8edb619936f02bc5089a5b9463e7d26b92919cf437a9aad8364c2ef57b80ceff97ead435976270fee69181a7344eec9b6",
          "sha256": "2445c9899cb92d88598a5699506393cbfd4c049bf901d87d26731459e07e9710",
          "sha1": "99129be12d0b026632b0d9b5402927a8b75ac744",
          "md5": "fabc608b832218bf52f43e523a16e536"
        }
      ]
    }
  ]
}
