{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc.remapper",
    "module": "mohistremapper",
    "version": "0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mohistremapper-0.3.jar",
          "url": "mohistremapper-0.3.jar",
          "size": 1862607,
          "sha512": "c355764c793b16ea351ba6736769fe1600ab07f4ce608912f24310bc3325f67d3cd019a3d8f3e6ca3b3c0bc672a1a008da1f05812e3c09456abfc2daf5f468a3",
          "sha256": "ecc10792a9b0df04d1f49bbbb62c62bb7e98eaa512b14ecd66da682a553a31a6",
          "sha1": "e12a038977730c2fa9ae1ce54669bf8bcaa84237",
          "md5": "327e55217d11b8c93c1f4bec14ddb3a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "net.md-5",
          "module": "SpecialSource",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "io.izzel",
          "module": "tools",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "cpw.mods",
          "module": "modlauncher",
          "version": {
            "requires": "10.0.8"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "mixin",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "cpw.mods",
          "module": "securejarhandler",
          "version": {
            "requires": "2.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "mohistremapper-0.3.jar",
          "url": "mohistremapper-0.3.jar",
          "size": 1862607,
          "sha512": "c355764c793b16ea351ba6736769fe1600ab07f4ce608912f24310bc3325f67d3cd019a3d8f3e6ca3b3c0bc672a1a008da1f05812e3c09456abfc2daf5f468a3",
          "sha256": "ecc10792a9b0df04d1f49bbbb62c62bb7e98eaa512b14ecd66da682a553a31a6",
          "sha1": "e12a038977730c2fa9ae1ce54669bf8bcaa84237",
          "md5": "327e55217d11b8c93c1f4bec14ddb3a3"
        }
      ]
    }
  ]
}
