# .github/workflows/dockflow-deploy.yml
name: Deploy
 
on:
  push:
    branches:
      - '*'
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx @dockflow-tools/cli deploy production "${{ github.ref_name }}-${{ github.sha }}"
        env:
          DOCKFLOW_SECRETS: ${{ toJSON(secrets) }}