{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "i18n",
    "version": "0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "i18n-0.4.jar",
          "url": "i18n-0.4.jar",
          "size": 3293,
          "sha512": "c5af0b0230ba881e6dc6a124e4267debf4145208aec617caee2e8fb2b7932d859c11b99a5014f95669949b7046e20f72968c1de6fffab847d3ea60ad496ac452",
          "sha256": "6308581a3116f571850c183eb50e9c724f136fa285bc09be828c637b672e1f0a",
          "sha1": "a9e75297797b3fc980f8ae8bddb9f103d518c896",
          "md5": "cb421a28f3e042d3a278e0f040b3094c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "i18n-0.4.jar",
          "url": "i18n-0.4.jar",
          "size": 3293,
          "sha512": "c5af0b0230ba881e6dc6a124e4267debf4145208aec617caee2e8fb2b7932d859c11b99a5014f95669949b7046e20f72968c1de6fffab847d3ea60ad496ac452",
          "sha256": "6308581a3116f571850c183eb50e9c724f136fa285bc09be828c637b672e1f0a",
          "sha1": "a9e75297797b3fc980f8ae8bddb9f103d518c896",
          "md5": "cb421a28f3e042d3a278e0f040b3094c"
        }
      ]
    }
  ]
}
